### ISSUE TITLE
我用的长城宽带无法正常访问mdui网站，每次都需要挂代理。我需要一份0.3.0的开发文档，不知道哪可以提供下载？

### ISSUE THREAD

**Issue by vsartly** [zdhxiong/mdui#103]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 0.3.0
---------------------------
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：如 Android、iOS、Windows、Linux、MacOS 等
* 浏览器及版本：如 Chrome 58.0.3029.110 (64-bit)
* 在线演示：你可以直接在这个模板上编辑：http://jsbin.com/nizivuwevu/edit?html,output

### 如何操作
我用的长城宽带无法正常访问mdui网站，每次都需要挂代理。我需要一份3.0的开发文档，不知道哪可以提供下载？

### 预期结果
你的操作期望的结果

### 实际结果
你的操作实际产生的结果

**Comment by zdhxiong** [comment]
你可以在这里下载离线版文档：https://github.com/zdhxiong/mdui-docs-builds
