### ISSUE TITLE
您好，这有一条关于响应适配的问题需要您的指导

### ISSUE THREAD

**Issue by zy5120** [zdhxiong/mdui#104]
首先感谢您开发如此优良的ui
在使用的过程中我遇到如下困惑..

当我在浏览器模拟分辨率访问页面时，显示正常
但是我用手机浏览器访问的时候，尽管是手机分辨率的界面，但是就像是电脑 把界面缩放了50%一样...试问如何解决呢？？

**Comment by zdhxiong** [comment]
检查你的 `<head>` 中是否添加了这行：
```html
<meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1.0, user-scalable=no"/>
```

**Comment by zy5120** [comment]
十分感谢。。。由于使用asp.net开发前端页，初次入门很多不懂。。
我刚刚翻阅了一下开发文档。。并没有找到关于这句话的意思。。。能请开发者告诉我一下这句话是啥意思吗。。

**Comment by zy5120** [comment]
问题解决。谢谢！
