### ISSUE TITLE
官网打不开呀，没人维护了吗？

### ISSUE THREAD

**Issue by why973828939** [zdhxiong/mdui#105]
如题，https://www.mdui.org官网是这个吧？打不开了，急用

**Comment by zdhxiong** [comment]
我测试是可以打开的，你是什么地区的什么宽带？

急需文档的话，可以在这里下载离线文档：https://github.com/zdhxiong/mdui-docs-builds

**Comment by why973828939** [comment]
get，thank you!

我这里现在的情况是这样的：
1、北京的联通和长城宽带都打不开
2、大概两周前都可以打开
3、其他人的电脑也打不开
4、页面显示无法访问此网站，响应时间过长
5、用公司的VPN也打不开

**Comment by zdhxiong** [comment]
大概一周前刚换了服务器，我用 17ce 测试的速度非常好，但现在已经有不少用户反馈打不开了。我再想其他解决办法吧。

**Comment by why973828939** [comment]
好的，辛苦辛苦

**Comment by manualof** [comment]
深圳电信，也经常给重置

**Comment by zdhxiong** [comment]
又对服务器做了调整，你们再测试一下能不能访问。

**Comment by yuan496** [comment]
还是能访问,
http://www.mdui.org:443/docs/

400 Bad Request

The plain HTTP request was sent to HTTPS port.

**Comment by zdhxiong** [comment]
@yuan496 怎么会带端口号的？

**Comment by dwb1994** [comment]
非常感谢 mdui 提供的中文文档，这次官网打不开，借此机会熟悉了英文文档

**Comment by lin-xin** [comment]
今天官网还是访问不了
