### ISSUE TITLE
关于模块化的bug

### ISSUE THREAD

**Issue by 0936zz** [zdhxiong/mdui#110]
---------------------------
这是一个（可多选）
* [x] bug 反馈
---------------------------

nodejs无法正常引入mdui
![image](https://user-images.githubusercontent.com/16662647/33483736-331b616a-d6da-11e7-9434-ba0f093af2e9.png)
![image](https://user-images.githubusercontent.com/16662647/33483707-17173fca-d6da-11e7-96e6-c2c75bbe6c9d.png)
经检测不赋值直接引入可用，但是不符合commonjs规范，应该是没有检测module对象直接赋值给了window

可参考
https://github.com/jquery/jquery/blob/master/src/wrapper.js#L19

**Comment by zdhxiong** [comment]
https://github.com/zdhxiong/mdui/commit/c4af979e8e1e3f16296c19101005886c6f4ccf8a
等下次发版本

**Comment by 0936zz** [comment]
神速
