### ISSUE TITLE
请问mdui的图标在本地上浏览可以，但放上服务器就不行了

### ISSUE THREAD

**Issue by liyuan98** [zdhxiong/mdui#111]
然后我在服务器的浏览器使用也是没问题的，我是windows server 2016，使用的是xampp，请问怎么设置

**Comment by zdhxiong** [comment]
打开控制台看看报了什么错。

**Comment by liyuan98** [comment]
是浏览器的控制台么？

**Comment by zdhxiong** [comment]
是

**Comment by liyuan98** [comment]
Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by liyuan98** [comment]
关于woff和woff2的错误11个，都是这句话

**Comment by liyuan98** [comment]
没错啊，如果错了，本地应该也用不了吧

**Comment by zdhxiong** [comment]
这个问题应该与mdui无关的。你自己想办法解决。或者你提供线上地址帮你看看。

**Comment by liyuan98** [comment]
线上地址是，网站地址还是服务器ip、密码

**Comment by zdhxiong** [comment]
网站地址

**Comment by liyuan98** [comment]
www.mingzai.name 是web前端技术课程的作业，做的丑见谅，谢谢

**Comment by zdhxiong** [comment]
CSS 路径改成 `./css/mdui.css`

**Comment by liyuan98** [comment]
你看看，我改了，好像还是不行

**Comment by zdhxiong** [comment]
http://www.mingzai.name/icons/material-icons/ 这个目录下不存在字体文件。

建议不要修改 mdui 的目录结构。

**Comment by liyuan98** [comment]
![l 9 r 5mclk0sg1 5_is](https://user-images.githubusercontent.com/34215670/34318141-cd2f802a-e7fa-11e7-9c3d-096f042d4f5a.png)
![m 2rbpns3 q 9 4c68cuad](https://user-images.githubusercontent.com/34215670/34318142-cd658dd2-e7fa-11e7-879d-bca8da6b4c0d.png)
![p6 _2m 6 m0 hi8e1](https://user-images.githubusercontent.com/34215670/34318143-cd9b7d0c-e7fa-11e7-851f-48fde06ed443.png)

**Comment by liyuan98** [comment]
一点儿都没改

**Comment by zdhxiong** [comment]
http://www.mingzai.name/icons/material-icons/MaterialIcons-Regular.woff2 这个文件确实不存在。
如果你服务器上存在这个文件，就可能是 apache 的配置问题了。

**Comment by zdhxiong** [comment]
参考一下这篇文章：http://www.yneit.com/2016/06/fontsfontawesome-webfont-woff2-404-not-found.html

**Comment by liyuan98** [comment]
好的，我看看

**Comment by liyuan98** [comment]
这个apache配置要怎么弄啊，加在哪里，我在文件里面比对了很多次，也试了很多次，还是不行

**Comment by zdhxiong** [comment]
网站根目录的 `*.htaccess` 文件中添加：
```
AddType application/font-woff            woff
AddType application/font-woff2           woff2
```

**Comment by liyuan98** [comment]
是新创一个后缀名为.htaccess的文件，里面添加
> 
AddType application/font-woff            woff
AddType application/font-woff2           woff2
> 
吗

**Comment by liyuan98** [comment]
命名有要求吗

**Comment by liyuan98** [comment]
感觉要崩溃了

**Comment by zdhxiong** [comment]
你自己找点文章看看吧
