### ISSUE TITLE
阿里云的cdn没有响应,导致官方主页无法渲染

### ISSUE THREAD

**Issue by KenMizz** [zdhxiong/mdui#113]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 0.3.0
---------------------------
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：如 Android、iOS、Windows、Linux、MacOS 等
* 浏览器及版本：如 Chrome 58.0.3029.110 (64-bit)
* 在线演示：你可以直接在这个模板上编辑：http://jsbin.com/nizivuwevu/edit?html,output

### 如何操作
请在这里详细说明你是如何操作导致的问题
在Windows 10上操作,打开Firefox(版本:58.0b10 64位)
输入网址:https://mdui.org
### 预期结果
你的操作期望的结果
网页成功渲染
### 实际结果
你的操作实际产生的结果
网页一片空白
(本人在美国)
![snipaste_2017-12-08_14-16-00](https://user-images.githubusercontent.com/16635884/33781374-5cf73cd2-dc22-11e7-9dc3-d1750440962a.png)

**Comment by PrintNow** [comment]
### MDUI 0.3.0 离线文档下载地址： [https://github.com/zdhxiong/mdui-docs-builds/releases](url)
### 自建 MDUI 0.3.0 文档： [https://doc.nowtime.cc/mdui](url)

**Comment by zdhxiong** [comment]
@KenMizz 你可以访问这个页面： https://cdn.dns-detect.alicdn.com/https/doc.html 检查一下网络状况

**Comment by KenMizz** [comment]
@zdhxiong 感谢
