### ISSUE TITLE
打包过后和开发环境控件的样式不一致

### ISSUE THREAD

**Issue by yanjingenious** [zdhxiong/mdui#116]
* 最新版 0.3.0
* 使用平台：Windows
* 浏览器及版本：Electron: 1.7.9	Node: 7.9.0	Chromium: 58.0.3029.110	V8: 5.8.283.38

我在vue的单文件组件中修改了button的样式，开发环境正常，打包过后组件设定的css貌似被框架的css给覆盖了

![qq 20171212020553](https://user-images.githubusercontent.com/19990773/33846345-64450444-dee1-11e7-86b9-3f513a6f9ea2.png)

最后发现要是不重写mdui的class就会产生上面的问题，开发环境正常，打包过后就gg
还发现如果改变了控件的大小，鼠标进入添加的背景会歪一点点，强迫症真受不了

**Comment by zdhxiong** [comment]
打开开发者工具看看怎么回事。没法调试我也不知道怎么回事。

**Comment by yanjingenious** [comment]
`mdui-btn-icon`
`mdui-icon`
我自己在组件里修改了这2个class后就正常了，打包后样式失效的问题就是这2个类的问题，自己添加的类会被这2个class覆盖
