### ISSUE TITLE
作者，你好！我用你的框架写了个b站视频下载的网站。发现两个问题

### ISSUE THREAD

**Issue by blogwy** [zdhxiong/mdui#122]
发现移动端获取不到数据，pc端可以。
ie浏览器也获取不到 但是edge可以
我的项目：https://github.com/blogwy/BilibiliVideoDownload
演示地址：http://www.bilibibi.cn/

**Comment by zdhxiong** [comment]
你的代码中用了 es6 的语法，IE 浏览器可能不支持

**Comment by blogwy** [comment]
还是不行，es6只是用了个模板字符串，都改成es5，还是一样的问题

**Comment by zdhxiong** [comment]
IE11 正常。IE10 不支持 let 语法，报错了。
