### ISSUE TITLE
在 Chrome 中遇到问题

### ISSUE THREAD

**Issue by rrfeng** [zdhxiong/mdui#123]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 0.4.0
---------------------------
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：MacOS 
* 浏览器及版本：Chrome 版本 63.0.3239.108（正式版本） （64 位）

### 如何操作
使用 Angular4 开发一个简单的 app，在 ngOnInit 的时候，如果检测到未登录，则创建一个 Dialog 并且用
 open() 开启，用于填写登录。
dialog 的按钮执行自定义的 login() 方法，成功后则执行 Dialog.close() 

### 预期结果
登录成功并且可以继续操作

### 实际结果
浏览器回退到了上一个页面。
如果使用前进按钮回到登录后的页面，是登录成功的，但是地址栏中有 /#&mdui-dialog 结尾。并且在这个页面中，操作任何的 dialog，到 dialog 关闭的时候（无论是 esc，close，还是 cancel），都会再次触发浏览器回退操作。

safari 没有回退，但是地址栏里保留了 /#&mdui-dialog 结尾

**Comment by zdhxiong** [comment]
设置 dialog 的参数 history 为 false，可以不改变 hash。

**Comment by rrfeng** [comment]
> 设置 dialog 的参数 history 为 false，可以不改变 hash。

确实解决了问题，能解释一下是为什么吗？正常状态下其他任何 dialog 都没出现过。只有在 ngOnInit 里初始化的这个会有这样的问题。

**Comment by zdhxiong** [comment]
应该是 bug，#84 已经提到了

**Comment by 4396NeverBeSlaves** [comment]
@zdhxiong  我的也是这样，而且设置history 为 false没有效果，地址栏依旧会出现#&mdui-dialog，点击按钮后就会后退到上一个页面。系统是win10,Chrome版本 63.0.3239.84
