### ISSUE TITLE
希望增加的几个组件

### ISSUE THREAD

**Issue by yh4922** [zdhxiong/mdui#124]
* 表单上传文件控件
* 侧拉菜单
---------------------------
* 这些经常使用的 希望能添加上去

**Comment by zdhxiong** [comment]
ajax 上传文件的话，mdui.JQ 支持的。上传的界面，Material Design 并没有涉及，可以自由发挥。
侧拉菜单的话，Drawer 组件设置 swipe 参数为 true 就能支持。

**Comment by chainwon** [comment]
为何不加个轮播呢

**Comment by yh4922** [comment]
我的意思是file控件的样式   你把表单的其他控件都弄了就是file控件没弄

**Comment by Angeliz** [comment]
觉得路径导航需求也蛮大的

**Comment by DongDavid** [comment]
辅助类中是否可以增加一个文本自动换行或者强制文本不换行的类，
因为我发现有个文本自动截断的类，但是上面换行或者不换行也是蛮常用的。
