### ISSUE TITLE
在 Angular4 中使用 [(ngModel)] 绑定内容的情况下无法使用 updateTextField()

### ISSUE THREAD

**Issue by rrfeng** [zdhxiong/mdui#125]
场景是这样：
有一个按钮，点击后会获取一些数据并弹出一个 dialog，数据和 dialog 中的文本框用 ngModel 双向绑定。然而有一个文本框是 textarea，它的默认高度是 1 行，但是数据获取到之后如果多于 1 行，那么初始渲染高度是只有 1 行的，必须点击一下文本框，才会重新渲染成合适的高度。自然就想用 updateTextField 来刷新一下，但是结果是内容全部变没了，而不是仅仅重画了 textarea 高度。

不确定这是一个 bug 还是 feature

**Comment by zdhxiong** [comment]
我对 Angular 不熟，无法直接进行测试。

调用 `mdui.updateTextFields()` 时，会先获取输入框的 value 值，进行一些操作后，再把值设置回输入框。你看看这个过程和 Angular 是否兼容。

**Comment by rrfeng** [comment]
好的谢谢。
