### ISSUE TITLE
请问有主题颜色选择的组件吗

### ISSUE THREAD

**Issue by PHPWZ** [zdhxiong/mdui#126]
有主题颜色选择的组件使用吗，官方有没有QQ群可以交流的

**Comment by zdhxiong** [comment]
没有

**Comment by PHPWZ** [comment]
分页呢

**Comment by zdhxiong** [comment]
有按钮组，可以当分页用

**Comment by PHPWZ** [comment]
主题选择颜色 是怎么实现的 老哥

**Comment by zdhxiong** [comment]
```
$('body').removeClass('旧的主题').addClass('新的主题')
```

**Comment by PHPWZ** [comment]
老哥，有联系方式吗，能请教下你吗

**Comment by zdhxiong** [comment]
我的github主页有我邮箱

**Comment by PHPWZ** [comment]
有什么办法让主题缓存吗，老哥，跟官网一样

**Comment by zdhxiong** [comment]
cookie

**Comment by PHPWZ** [comment]
我用官网的缓存js，并不能设置cookie缓存呐
`  var setCookie = function (key, value) {
    // cookie 有效期为 1 广
    var date = new Date();
    date.setTime(date.getTime() + 365*24*3600*1000);
    document.cookie = key + '=' + value + '; expires=' + date.toGMTString() + '; path=/'; 
  };`

**Comment by zdhxiong** [comment]
官网是在后端读取 cookie，把主题的 class 写到页面模板里的。

**Comment by PHPWZ** [comment]
知道了

**Comment by PHPWZ** [comment]
有后台的模板吗

**Comment by zdhxiong** [comment]
没有

**Comment by PHPWZ** [comment]
没事，我自己写吧，打算用mdui写社区项目

**Comment by zdhxiong** [comment]
加油，mdui 的官方社区也在开发中了

**Comment by PHPWZ** [comment]
建议建个QQ群

**Comment by PHPWZ** [comment]
TP5写的

**Comment by peterpei1186861238** [comment]
不是mdui官网有颜色选择？
我直接扒了
