### ISSUE TITLE
按钮添加工具提示后用JS禁用该按钮导致工具提示不消失

### ISSUE THREAD

**Issue by itning** [zdhxiong/mdui#127]
* [x] bug 反馈
* 使用平台：Windows
* 浏览器及版本： Chrome  63.0.3239.132（正式版本） （64 位）
* 在线演示：
https://gist.github.com/anonymous/6d6c9ed25a741d699f4a90e4fc78ea2c
http://output.jsbin.com/pasogenahi
### 如何操作
按钮添加工具提示后用JS禁用该按钮导致工具提示不消失

### 预期结果
工具提示正常消失

### 实际结果
工具提示不消失

**Comment by zdhxiong** [comment]
工具提示和按钮的禁用状态无关。你可以在禁用按钮后移除 `mdui-tooltip` 属性。

**Comment by itning** [comment]
你好,是工具提示提示的内容不消失,例如我现在禁用这个按钮了,当我鼠标放上去的时候工具提示的提示正常显示,但是鼠标移走,这个提示并不会消失,而是还会在显示在原地,我现在想让它工具提示正常提示在按钮被禁用后

**Comment by zdhxiong** [comment]
好的，我现在手边没电脑，等我明天在电脑上测试一下。

**Comment by itning** [comment]
好的 非常感谢 出错的情况我已经放在在线演示中了

**Comment by zdhxiong** [comment]
因为被禁用的元素上无法触发鼠标事件，导致了这个问题。

我看了其他主流框架，都存在这个问题，解决方法就是在禁用的元素外面再包裹一个元素，把 `mdui-tooltip` 放到父元素上。

**Comment by itning** [comment]
好的 非常感谢!
