### ISSUE TITLE
select 在 dialog 中无法正常显示

### ISSUE THREAD

**Issue by 0936zz** [zdhxiong/mdui#129]
![image](https://user-images.githubusercontent.com/16662647/35041116-957f6910-fbbe-11e7-810a-a93a1b285a7d.png)
在mdui.dialog中使用下拉菜单会因为长度不够而导致select不能完全显示

**Comment by zdhxiong** [comment]
你可以在 `.mdui-dialog` 和 `.mdui-dialog-content` 上加上  `style="overflow: visible"` 临时解决这个问题。
后续会进行一些优化

**Comment by 0936zz** [comment]
好吧，我先用原生的吧

还有一个问题，文本框鼠标指针样式为什么从text变成了cursor，而且文本框的颜色也变黑了
![image](https://user-images.githubusercontent.com/16662647/35088953-62841468-fc70-11e7-8477-6c1609955e20.png)

**Comment by zdhxiong** [comment]
设计规范就是 cursor，文本框的颜色是 a700，比标准强调色深一点。

**Comment by 0936zz** [comment]
![image](https://user-images.githubusercontent.com/16662647/35099101-b7d8fbc4-fc91-11e7-894c-cc56b84c9dbd.png)
我去谷歌官方的mdlite库看了一下，颜色是强调色，指针也是text，规范了也并没有说啊
而且按照用户体验来说的话，文本框还是用text比较好，cursor给人的感觉都是点了会有什么功能一类的

**Comment by zdhxiong** [comment]
mdlite 并不符合规范。

文档都是有提到的：

![image](https://user-images.githubusercontent.com/3030330/35099623-a59c6c50-fc93-11e7-8203-1a9f60475302.png)

![image](https://user-images.githubusercontent.com/3030330/35099635-b3702c04-fc93-11e7-9508-de71ac65d33f.png)

**Comment by 0936zz** [comment]
这个规范好奇怪啊，不按常理出牌
