### ISSUE TITLE
按钮/列表之类在Firefox点击出现虚线框（google家的plus之类的不会有）

### ISSUE THREAD

**Issue by weijarz** [zdhxiong/mdui#132]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 0.4.0
---------------------------
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：如 Android、iOS、Windows、Linux、MacOS 等
Linux

* 浏览器及版本：如 Chrome 58.0.3029.110 (64-bit)
Firefox 57

* 在线演示：
比如点 https://www.mdui.org/docs/button 这个页面上的按钮。

### 如何操作
点击按钮或列表，周边会有一圈虚线。

### 预期结果
Google家的应用比如Plus没有这个虚线框。

**Comment by zdhxiong** [comment]
并没有发现这种情况

**Comment by weijarz** [comment]
@zdhxiong 
我指的是这种虚线框(Firefox特有），在按下时出现，Google的没有。
![screenshot from 2018-01-25 10-01-23](https://user-images.githubusercontent.com/8944061/35366946-dc9afb40-01b6-11e8-869f-10b393f3939a.png)

**Comment by weijarz** [comment]
@zdhxiong 我之前给vuetify也提过这个问题
https://github.com/vuetifyjs/vuetify/issues/1843
你可以参考下他们的修复。
