### ISSUE TITLE
复选框的默认颜色怎么改呀orz

### ISSUE THREAD

**Issue by Angeliz** [zdhxiong/mdui#133]
就是设置了主题色之后，复选框组件选中后的默认颜色一直是原来的粉色，要怎样才能调成自己想要的颜色呢？

**Comment by zdhxiong** [comment]
复选框用的是强调色。
例如在 body 添加 mdui-theme-accent-blue，复选框就会变蓝色

**Comment by Angeliz** [comment]
谢谢谢谢！
