### ISSUE TITLE
在含有文本框的页面中控制台输出 test

### ISSUE THREAD

**Issue by yrccondor** [zdhxiong/mdui#136]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 0.4.0
---------------------------
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：Android、Windows
* 浏览器及版本：Chrome 63.0.3239.132 (64-bit)
* 在线演示：无

### 如何操作
打开一个含有文本框的、由 MDUI 构建的页面

### 实际结果
浏览器控制台输出 `test`。此问题在自行开发的项目和 MDUI 文档中均能复现。

**Comment by zdhxiong** [comment]
https://github.com/zdhxiong/mdui/commit/824cfe60907cbb8d0d833647bf4babf7c496ffee
