### ISSUE TITLE
模版收录

### ISSUE THREAD

**Issue by qq690712575** [zdhxiong/mdui#137]
---------------------------
* [x] 功能建议
* [ ] 新组件或新特性
---------------------------
不知道作者有没打算收录mdui做的模板，我从mdui1.0开始使用至今4.0已经用过多种页面上使用，特别移动端。手头上也有不少项目是基于MDUI构建的，但对于其他框架来说少了写模板页面，可以使其他人员直接下载后就用，例如登陆页，后天管理页等。

**Comment by KeJunMao** [comment]
支持

**Comment by zdhxiong** [comment]
目前已经在加紧开发社区了，之后会努力完善生态的。

**Comment by xbmanh** [comment]
http://mdcui.com/demo/toolbar/waterfall-flexible-toolbar.html

**Comment by DFFZMXJ** [comment]
@xbmanh 我知道怎么用滚动改变字体大小和状态栏颜色、阴影，就是不知道怎么让标题改变位置。
