### ISSUE TITLE
menu和button可以设计为不必须放在同一元素下吗

### ISSUE THREAD

**Issue by springmarker** [zdhxiong/mdui#14]
有多个button，想打开同一menu，但是menu必须放在和button同一元素下，不然会报错，这样每个button旁边都要写一个menu，比较麻烦和影响美观，所以可以设计为不必须放在同一元素下吗

**Comment by zdhxiong** [comment]
因为菜单要根据父元素进行定位，所以必须和按钮在同一元素下。目前没法做到不在同一元素下。
