### ISSUE TITLE
开/关切换 组件在自行切换 checked 属性后出错

### ISSUE THREAD

**Issue by yrccondor** [zdhxiong/mdui#140]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 0.4.0
---------------------------
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：Android、Windows
* 浏览器及版本：Chrome 65

### 如何操作
在页面中使用 开/关切换 组件，通过自己编写的 js 切换了 `checked` 属性。

### 预期结果
无论是自行编写 js 来切换开关状态还是通过点击 开/关切换 组件 来切换开关状态，此组件应均能正常工作。

### 实际结果
在通过自行编写的 js 切换 `checked` 属性后再次点击此 开/关切换 组件时，从控制台看到 `checked` 属性被切换，但无动画效果。

**Comment by zdhxiong** [comment]
http://jsbin.com/seyufapoqi/edit?html,output
我试了，没有问题

**Comment by yrccondor** [comment]
http://jsbin.com/nosoxucizo/edit?html,output
请看这个例子，使用了 jQuery
只要多点几下，动画就会消失，但 `checked` 属性依然可以正常切换。

**Comment by zdhxiong** [comment]
用 `jQuery` 的 `attr` 操作 `checked` 属性可能会有问题，你审查元素看到 `checked` 属性变化了，但在控制台输入 `$('#tc-autorun').is(':checked')` 可以看到其实并没有变化。

用 `prop` 操作应该不会有问题。

**Comment by yrccondor** [comment]
好的感谢
