### ISSUE TITLE
在tab里动态添加a，调用mdui.mutation()无效果

### ISSUE THREAD

**Issue by zhuxinghan** [zdhxiong/mdui#141]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 0.4.0
---------------------------
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：Windows
* 浏览器及版本：桌面浏览器
* 在线演示：你可以直接在这个模板上编辑：http://jsbin.com/quzokezoko/edit?html,output

### 如何操作
页面加载后，使用js往.mdui-tab元素里动态添加a元素，然后调用mdui.mutation()

### 预期结果
新添加的a元素和原来的a元素一样可以切换

### 实际结果
新添加的a元素不正常工作，点击不会高亮，只有写在页面html里的才可以

感谢您和您的mdui。大致看了一下源码，发现mutation方法只处理新添加的tab，不处理已有tab里新添加的a元素

**Comment by zdhxiong** [comment]
更新已有的 Tab，需要调用 `handleUpdate()` 方法

**Comment by zhuxinghan** [comment]
不好意思，没有仔细阅读文档😂
