### ISSUE TITLE
关于设置强调色的问题

### ISSUE THREAD

**Issue by pheeno** [zdhxiong/mdui#142]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 0.4.0
---------------------------
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：如 Android、iOS、Windows、Linux、MacOS 等
* 浏览器及版本：如 Chrome 58.0.3029.110 (64-bit)
* 在线演示：你可以直接在这个模板上编辑：http://jsbin.com/quzokezoko/edit?html,output

### 如何操作
在body中设置了强调色

### 预期结果
强调色是否可以设置饱和度,比如在文本框中，focus后的颜色

### 实际结果
用了其他方法设置，但是没有成功，又不想改源码

**Comment by zdhxiong** [comment]
组件默认的颜色无法设置饱和度

**Comment by pheeno** [comment]
收到，感谢！



kyatth@163.com
 
发件人： zdhxiong
发送时间： 2018-04-19 01:01
收件人： zdhxiong/mdui
抄送： pheeno; Author
主题： Re: [zdhxiong/mdui] 关于设置强调色的问题 (#142)
Closed #142.
