### ISSUE TITLE
跟 Angular 一起用问题很多啊…

### ISSUE THREAD

**Issue by rrfeng** [zdhxiong/mdui#143]
* 请确保你使用的是最新版的 mdui，当前最新版为 0.4.1
---------------------------
这是一个（可多选）
* [x] bug 反馈
---------------------------
除了 #125 提到的 input 的问题，还有如果使用了 ng router，路由切换返回后：
- TAB 选项卡会异常，全部展示出来而不是只展示选中的
- Collapse 子列表无法再展开、收起，点击无效

**Comment by rrfeng** [comment]
经过尝试在 ngAfterContentInit 中 mutation 可以解决上述两个问题。

**Comment by mayue1020** [comment]
vuejs也遇到了类似问题，在mounted里添加`mdui.mutation()`正常了
