### ISSUE TITLE
表格控件msui-table-selectable类失效

### ISSUE THREAD

**Issue by fanxinjie** [zdhxiong/mdui#145]
使用mdui-table-selectable类失效，并不能在表格的每一行首部自动添加checkbox

**Comment by fanxinjie** [comment]
基于AngularJS使用mdui，会出现上述问题

**Comment by zdhxiong** [comment]
首次初始化页面需要调用 `mdui.mutation()`
更新表格后需要调用 `mdui.updateTables()`
