### ISSUE TITLE
希望弹出对话框的时候，不要锁定页面的宽度

### ISSUE THREAD

**Issue by zhuxinghan** [zdhxiong/mdui#149]
---------------------------
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------

弹出对话框时，body 被设置了固定宽度，这样在对话框显示期间，如果修改了浏览器窗口大小，对话框下的内容不响应窗口大小变化，而是在对话框关闭时突然重排，给人唐突的感觉。目前我订阅对话框打开完成事件，移除 body 的固定宽度，也没发现有什么副作用。
还有，对话框的垂直居中好像用的是 js 算的绝对定位，窗口大小改变时，对话框明显有个先水平居中，后垂直居中的两步跳的过程，希望能使用 css 定位。

**Comment by zdhxiong** [comment]
打开对话框后会在 body 上添加 `overflow:hidden`，使页面不能滚动，这时滚动条会消失，页面宽度会变宽（在原有宽度上加上了滚动条宽度），这会导致每次打开和关闭对话框，页面都会重排。为了避免这种情况，就需要在打开对话框前，把 body 设为固定宽度。

因为框架需要兼容到 IE10，但 IE10 对 flex 的支持不好，所以用了 js 进行垂直居中。

**Comment by zhuxinghan** [comment]
`overflow: hidden` 屏蔽滚动好像只对鼠标滚轮有效，在手机上还是能滚动。而且既然用户滚动了鼠标滚轮，对话框下的内容发生滚动也是可以接受的行为。所以屏蔽滚动是不是不必要的呢？
如果确实想屏蔽鼠标滚动，倒不如在对话框打开之后，对 `wheel` 事件做 `preventDefault()`。

**Comment by zdhxiong** [comment]
`overflow: hidden` 对手机也是有效的。
打开了对话框，焦点就在对话框上了，滚动滚轮是对对话框内容的滚动，不是滚动页面。阻止 `wheel` 更是不可能的。

**Comment by zhuxinghan** [comment]
我在安卓手机和 iPhone 上打开 MDUI 官网，打开一个对话框，对话框下的页面都是能用手指滚动的。

难道设置 `overflow: hidden` 的目的不是屏蔽对话框下的页面滚动吗？

如果不设置 `overflow: hidden` 和 body 上的固定宽度，而是使用 `document.querySelector(".mdui-overlay").addEventListener("wheel", function(e) { e.preventDefault(); });`，既能防止鼠标滚轮滚动对话框下的页面，但不影响滚动对话框内容，也没有对话框显隐时滚动条显隐导致的重排，并且让页面在对话框打开时也响应窗口大小改变。

比如打开 https://www.mdui.org/docs/dialog，打开右上角的“设置主题”对话框，然后执行这三句代码：
`document.body.style.overflow = "auto";`
`document.body.style.width = "";`
`document.querySelector(".mdui-overlay").addEventListener("wheel", function(e) { e.preventDefault(); });`
就能看到效果了，我想表达的就是这个意思。
