### ISSUE TITLE
请问如何实现卡片的横向布局？

### ISSUE THREAD

**Issue by Zarmot** [zdhxiong/mdui#150]
---------------------------
这是一个（可多选）
* [ ] bug 反馈
* [x] 功能建议
* [ ] 新组件或新特性
---------------------------
![效果图](http://wx4.sinaimg.cn/mw690/0060lm7Tly1fr4bto010kj31680da3zp.jpg)
这张图片来自设计规范的“卡片”页面，我希望使用这种横向布局，但MDUI的文档中卡片都是纵向布局，请问是否能够实现这种效果？

**Comment by Zarmot** [comment]
修正一下，也不算横向布局，这实际上也是一个纵向布局，只是边上附了一张图片，这种效果能实现么

**Comment by zdhxiong** [comment]
框架不带这种样式，你需要自己写样式实现
