### ISSUE TITLE
模态框 - 半透区域点击的逻辑问题

### ISSUE THREAD

**Issue by lqzhgood** [zdhxiong/mdui#151]
---------------------------
这是一个（可多选）
* [ ] bug 反馈
* [x] 功能建议
* [ ] 新组件或新特性
---------------------------
### 预期结果
模态框 - 半透区域   点击后 的逻辑应该等同于取消，触发 cancel.mdui.dialog 事件。
或者单独增加一个 触发事件 

### 实际结果
目前仅会关闭模态窗，不会触发任何事件

**Comment by zdhxiong** [comment]
`cancel.mdui.dialog` 事件只在点击含 `mdui-dialog-cancle` 属性的按钮时才会触发。
点遮罩区域关闭会触发 `close.mdui.dialog` 和 `closed.mdui.dialog` 事件的。
