### ISSUE TITLE
Chrome自动表单填充时浮动的label无法自动浮动

### ISSUE THREAD

**Issue by postbird** [zdhxiong/mdui#154]
---------------------------
这是一个（可多选）
* [x] bug 反馈
---------------------------
* 使用平台：Widnows
* 浏览器及版本： Chrome 58.0.3029.110 (64-bit)
* 在线演示：无

### 如何操作
Chrome自动表单填充下，使用了 `mdui-textfield-floating-label` 的浮动标签不会自动浮动

**但是F5刷新，label会浮动，而直接访问页面，不会浮动**

### 预期结果
判断是否表单内容自动填充后，自动浮动label

### 实际结果

![image](https://user-images.githubusercontent.com/16200574/40276496-4a7fbee8-5c3e-11e8-8935-51c70b09731c.png)

**Comment by DFFZMXJ** [comment]
使用`mdui.updateTextFields()`初始化输入框元素。

**Comment by zdhxiong** [comment]
chrome 在自动填充表单时，并不会触发事件，也无法用 JS 获取到输入框的值，所以貌似没有办法解决这个问题。
