### ISSUE TITLE
手机显示内容比较多的表格，会显示不全

### ISSUE THREAD

**Issue by Rsplwe** [zdhxiong/mdui#156]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 0.4.1
---------------------------
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：Android
* 浏览器及版本：Chrome | 61.0.3163.98 (正式版本) （32 位）

### 预期结果
xxxxxxx

### 实际结果
手机显示内容比较多的表格，会显示不全，电脑版就没有这个问题

[https://i.loli.net/2018/05/24/5b0656097a38a.png](url)

**Comment by zdhxiong** [comment]
你可以自己调试一下，或者升级浏览器版本后再试。
