### ISSUE TITLE
上传到cos存储调用跨域访问错误No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by luochenzhimu** [zdhxiong/mdui#157]
Access to Font at 'https://***.com/public/mdui/fonts/roboto/Roboto-Regular.woff2' from origin 'https://******.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://******.com' is therefore not allowed access.
(index):1 
Access to Font at 'https://***/public/mdui/icons/material-icons/MaterialIcons-Regular.woff2' from origin 'https://******.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://******.com' is therefore not allowed access.
(index):1 
Access to Font at 'https://***.com/public/mdui/fonts/roboto/Roboto-Regular.woff' from origin 'https://******.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://******.com' is therefore not allowed access.
(index):1 
Access to Font at 'https://***/public/mdui/icons/material-icons/MaterialIcons-Regular.woff' from origin 'https://******.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://******.com' is therefore not allowed access.

**Comment by zdhxiong** [comment]
与mdui无关的问题，请自行解决

**Comment by luochenzhimu** [comment]
@zdhxiong 解决了，谢谢解答
cdn HTTP Header配置里面添加了Access-Control-Allow-Origin参数就好了
