### ISSUE TITLE
与vue 单页面应用一起使用时存在的问题

### ISSUE THREAD

**Issue by yyyuuu777** [zdhxiong/mdui#16]
有几个问题 想请教一下
 .1 我用 vue 搭建的spa 项目,在main.js 中把 mdui.js 导入了，但是路由改变之后,tab 切换等效果就不起作用了，需要重新 new 一下组建，不然的话 就调到 a 设置的target链接的地方了，希望仔细回答一下,困扰好久了..

**Comment by zdhxiong** [comment]
我没用过 vue，不知道 vue 路由的原理。
如果路由改变后会导致页面重新渲染的话，MDUI 的组件也要重新初始化。
现在给不了你建议，等我以后学了 vue，再来重新测试一下在 vue 中使用 MDUI。

**Comment by yyyuuu777** [comment]
你用什么聊天工具,可以加我个qq吗,444832384~~

**Comment by achun** [comment]
@yyyuuu777 看下 #94, 看是不是满足你的需求
