### ISSUE TITLE
展开提示错误

### ISSUE THREAD

**Issue by DSYliangweihao** [zdhxiong/mdui#161]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 0.4.1
---------------------------
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：如 Android、iOS、Windows、Linux、MacOS 等
* 浏览器及版本：如 Chrome 58.0.3029.110 (64-bit)
* 在线演示：你可以直接在这个模板上编辑：http://jsbin.com/quzokezoko/edit?html,output

### 如何操作
请在这里详细说明你是如何操作导致的问题
  .height($content[0].scrollHeight)
collapse.js:140 Uncaught TypeError: Cannot read property 'scrollHeight' of undefined
    at t.open (collapse.js:140)
    at t.toggle (collapse.js:190)
    at HTMLDivElement.<anonymous> (collapse.js:52)
    at u (event.js:261)
    at event.js:276
    at Array.forEach (<anonymous>)
    at HTMLDivElement.a.proxy (event.js:274)
### 预期结果
你的操作期望的结果
之前还能使用 后来就报出这个错误
### 实际结果
你的操作实际产生的结果

**Comment by zdhxiong** [comment]
请给出在线示例代码，否则无法解答
