### ISSUE TITLE
mdui内置滚动条，能加入文档给开发使用吗

### ISSUE THREAD

**Issue by lky5230** [zdhxiong/mdui#162]
mdui内置滚动条，能加入文档给开发使用吗

**Comment by zdhxiong** [comment]
滚动条样式默认是全局生效的，不需要使用方法。

**Comment by lky5230** [comment]
@zdhxiong 我想给body标签也加上mdui内置的滚动条如何呢

**Comment by zdhxiong** [comment]
可以参考 https://github.com/zdhxiong/mdui/blob/21ac113c92acb9f52ac56f926495499d2b7a9eb1/src/global/less/base.less#L19

**Comment by lky5230** [comment]
@zdhxiong tks，git it
