### ISSUE TITLE
对于draggable 属性样式不正确

### ISSUE THREAD

**Issue by yrccondor** [zdhxiong/mdui#164]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 0.4.1
---------------------------
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：Windows
* 浏览器及版本：Chrome 68 (64-bit)
* 在线演示：http://jsbin.com/ferijijese/edit?html,output

### 如何操作
将鼠标移至 `.mdui-typo` 中任意带有 `draggable="false"` 属性的元素上

### 预期结果
鼠标样式不变

### 实际结果
出现拖动鼠标

据 MDN 文档：
> 这个属性是枚举类型，而不是布尔类型 。这意味着必须显式指定值为 true 或者 false 

MDUI 使用 `.mdui-typo [draggable]` 选择器并不是太合适

**Comment by zdhxiong** [comment]
已修复 1c49a9d078118ad2bca881c82b046792e9f3fb59

**Comment by zdhxiong** [comment]
已修复 1c49a9d078118ad2bca881c82b046792e9f3fb59
