### ISSUE TITLE
鼠标移动到文本框的时候会呈现手形而非 I 形

### ISSUE THREAD

**Issue by t123yh** [zdhxiong/mdui#175]
* [x] bug 反馈

https://www.mdui.org/docs/textfield

平台：Linux KDE Chrome 69

### 如何操作
在文本框里随便输入一点字，把鼠标移动到文本框上

### 预期结果
鼠标呈现 I 形
![image](https://user-images.githubusercontent.com/8972552/45407634-97a31180-b69c-11e8-8a34-b98a49b71831.png)

### 实际结果
鼠标呈现点击超链接时的手形
![image](https://user-images.githubusercontent.com/8972552/45407668-b1dcef80-b69c-11e8-8721-142b53f31e87.png)

**Comment by zdhxiong** [comment]
这是旧版的 Material Design 规范：
![menu saveimg savepath20180912150916](https://user-images.githubusercontent.com/3030330/45408064-db4a4b00-b69d-11e8-99c4-03f600a5b447.jpg)


这是新版 Material Design 规范：
![textfields-filled-states](https://user-images.githubusercontent.com/3030330/45408115-fddc6400-b69d-11e8-8734-6f7f5440179f.png)

**Comment by t123yh** [comment]
很奇怪，不知道 Google 为什么要这样设计。
