### ISSUE TITLE
动态元素与Angular配合的问题

### ISSUE THREAD

**Issue by 805447391** [zdhxiong/mdui#178]
使用Angular模块制作单页面应用，http请求是异步的，ng模版的加载也是异步的，请问选择mutation的时机是否有技巧？现在很多界面的动态元素都是无效的，例如：table的selectable属性，下拉菜单的动画效果等。
望回复，谢谢 :>

**Comment by 805447391** [comment]
补充一下：
Angular DOM加载完毕调用动态方法：
$scope.$on('$viewContentLoaded', function () { // $on可以换成$watch
        mdui.mutation();
});

ng-repeat后DOM加载完毕调用动态方法：
引用：https://www.cnblogs.com/jach/p/5734964.html

table的selectable需要调用两步：
mdui.mutation();
mdui.updateTables();

**Comment by zdhxiong** [comment]
`mdui.mutation()` 用于对未初始化的元素进行初始化，`mdui.updateTables()` 用于对已初始化后，又修改过的元素进行重新初始化。
