### ISSUE TITLE
文本框下方空白展示bug

### ISSUE THREAD

**Issue by crucialize** [zdhxiong/mdui#181]
* [√] 我使用的是 0.4.1 版本的mdui
---------------------------
这是一个（可多选）
* [√] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 浏览器及版本：**所有**浏览器

### 如何操作

我在mdui的基础上用了最流行的表单合法性检验jq插件——jquery-validation，却发现了非常影响美观的bug。

jquery-validation的工作流程是：用户的输入不合法，就在输入框下方（同层的地方），添加一个特定class的标签，只包含提示信息。

所以我理所当然的将这个特定类(errorClass)设置为mdui-textfield-error。（插一句，jq-validation会将input与label同时设置为errorClass，导致input样式混乱，所以我在jq-validator的参数里加上highlight参数以去掉input的errorClass。你在做实验的时候要注意到这点，不然又是一个新的问题）。

### 结果

然后出现结果：文本框与提示信息重合了。

然后我点击那个输入框，然后再点到空白区域，结果提示信息下移了，显示正常了。

一查原因，发现input的父元素(div)多了一个类： mdui-textfield-has-bottom。这个东西应该是来添加空白区域的，只不过出现的时机晚了点。在任何时候执行mdui.mutation()都无法解决这个问题，只有预先在div上面加上mdui-textfield-has-bottom，一切才会正常。

### 结论
- 在input下方新添加的label(div同样会)，即使类为mdui-textfield-error，也会与输入框重合。
- 点输入框再点其他地方，两元素会变得正常。

### 其他信息：
我只引用了jquery最新版、jquery.validation及其语言包最新版、mdui最新版css和js。

**Comment by zdhxiong** [comment]
`mdui-textfield-has-bottom` 只有在有 `mdui-textfield-helper` 或 `mdui-textfield-error` 时才会被添加。
因为你的文本框初始化时不存在这两个 class，你可以手动添加 `mdui-textfield-has-bottom`。
