### ISSUE TITLE
关于下拉选择的问题<select>

### ISSUE THREAD

**Issue by aefj11** [zdhxiong/mdui#184]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 0.4.1
---------------------------
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：Windows 7
* 浏览器及版本：版本 70.0.3538.110（正式版本） （64 位）

### 如何操作
我使用的是aurelia框架，类似于angularjs，在进行select绑定时，发现找不到绑定的内容，去掉mdui-select以后显示就正常了，不知道这是什么导致的，您有好点的建议吗？
这个是源代码
![image](https://user-images.githubusercontent.com/24756208/49740340-e9286000-fcce-11e8-8d88-2a10d9895e3d.png)
这个是没解决的BUG图
![image](https://user-images.githubusercontent.com/24756208/49740408-0fe69680-fccf-11e8-82cd-52667eb8ae74.png)
这个是去掉mdui-select以后的代码
![image](https://user-images.githubusercontent.com/24756208/49740610-900cfc00-fccf-11e8-9172-48db4fdb713c.png)
### 预期结果
给一个好些的建议或者修复BUG

**Comment by zdhxiong** [comment]
因为 select 元素是动态生成的，你需要在 DOM 生成后，使用 `mdui.mutation()` 来初始化 select。

我在 aurelia 官方的例子上做了演示：
https://codesandbox.io/s/ko3v54p9rr

**Comment by aefj11** [comment]
我在您例子的基础上做了些修改，复现了我现在的问题，您看下

https://codesandbox.io/s/912ylkr784

**Comment by zdhxiong** [comment]
`mdui.mutation()` 的作用是对未实例化的元素进行实例化，已实例化的元素再次调用该方法则不会起作用。
你的第二个 select 是在实例化之后修改了内容，应该调用 Select 实例的 `handleUpdate` 方法来重新生成下拉框。

我在你的基础上做了修改：
https://codesandbox.io/s/jp1y98mwy5

另外，在 select 元素只有一个选项时，下拉框高度过高，这是 mdui 的 bug，我会尽快修复。

**Comment by aefj11** [comment]
问题已经解决了，感谢您
