### ISSUE TITLE
js 放在 head 里 spinner 无法显示

### ISSUE THREAD

**Issue by liberize** [zdhxiong/mdui#185]
最新版 0.4.2
---------------------------
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：Windows
* 浏览器及版本：Chrome 71.0.3578.98 (Official Build) (64-bit)

### 如何操作

https://www.mdui.org/docs/progress/demo3

把这个 demo 里 script tag 移到 head 里

### 预期结果

spinner 可以正常显示

### 实际结果

spinner 不显示

PS: script tag 加上 defer 或者放在 body 最后面没有问题

**Comment by liberize** [comment]
好歹回复一下吧，直接 close，原因都不说

**Comment by zdhxiong** [comment]
https://github.com/zdhxiong/mdui/commit/cc4f8ef1181b737590779c0c6fa6b2e3eb2dcf04 刚刚修复了

**Comment by liberize** [comment]
OK
