### ISSUE TITLE
prompt bug

### ISSUE THREAD

**Issue by angelop007** [zdhxiong/mdui#190]
dialog.prompt.js:73
---------------------------
* [x] bug 反馈
---------------------------
* 使用平台：Windows 
* 浏览器及版本：Chrome 72.0.3626.81（正式版本）（64 位）
* MDUI版本：0.4.2
---------------------------
引用CDN
`https://cdn.bootcss.com/mdui/0.4.2/`
`https://cdn.jsdelivr.net/npm/mdui@0.4.2/`
均有问题，但是去看了官方的调试页面引用的
`https://mdui-aliyun.cdn.w3cbus.com/source/dist/css/mdui.min.css`
就没问题，我也引用了下aliyun的CDN也没问题。。。

报错如下图：
![20190302213258](https://user-images.githubusercontent.com/12540515/53682650-ca1bf600-3d32-11e9-9f2a-ce9bf0e8cd8d.png)

代码大致如下：
```javascript
mdui.prompt('请输入',
    val=>{
         // do it
    },()=>{},{
         confirmText:'确认',
         cancelText:'取消',
         maxlength:8,
         confirmOnEnter:true
    }
);
```
点击确定或取消均报错！

**Comment by zdhxiong** [comment]
v0.4.3 已修复
