### ISSUE TITLE
在vue中偶尔跳转，偶尔不跳转[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. 

### ISSUE THREAD

**Issue by clouddemo1** [zdhxiong/mdui#193]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 0.4.1
提示mdui.js 1570行的事
---------------------------
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：如 Android、iOS、Windows、Linux、MacOS 等
* 浏览器及版本：如 Chrome 58.0.3029.110 (64-bit)
* 在线演示：你可以直接在这个模板上编辑：http://jsbin.com/quzokezoko/edit?html,output

### 如何操作
请在这里详细说明你是如何操作导致的问题

### 预期结果
你的操作期望的结果

### 实际结果
你的操作实际产生的结果

**Comment by zdhxiong** [comment]
你遇到什么问题了？把问题描述出来

**Comment by clouddemo1** [comment]
谢谢作者，不好意思不是bug偶尔跳转偶尔不跳已经解决了。
不过打开Chrome的All Levels会出MDUI 1570行这个警告，让我误以为是MDUI的问题。
![mdui1570](https://user-images.githubusercontent.com/50731051/58545692-58bae900-8236-11e9-9a63-0366386129be.png)
