### ISSUE TITLE
在Vue Cli3中如何使用npm install 安装的MDUI？

### ISSUE THREAD

**Issue by clouddemo1** [zdhxiong/mdui#194]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 0.4.1
---------------------------
这是一个（可多选）
* [] bug 反馈
* [x] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：如 Android、iOS、Windows、Linux、MacOS 等
* 浏览器及版本：如 Chrome 58.0.3029.110 (64-bit)
* 在线演示：你可以直接在这个模板上编辑：http://jsbin.com/quzokezoko/edit?html,output

### 如何操作
请在这里详细说明你是如何操作导致的问题

### 预期结果
你的操作期望的结果

### 实际结果
你的操作实际产生的结果

我使用的是Vue Cli3 脚手架生成的项目，现在在index.html里面用CDN方式的能用，但是我想用本地的。
我先用npm install mdui -S 安装了，然后我搜到这个问答：https://www.mdui.org/questions/9 按照这种方法像用上

在main.js里加上这个 
···
import 'mdui/dist/css/mdui.css'; // 注意修改 css 文件的路径（这个应该是node_modules下面的路径）
import mdui from 'mdui';
···
在App.vue里加上
···
import mdui from 'mdui';
···

结果还是不好用。。请教下应该怎么用？

**Comment by clouddemo1** [comment]
又试了下，是不是每个组件里都要加上 import mdui from 'mdui';？ 每个都加上这回貌似好了。。

**Comment by zdhxiong** [comment]
是的。在用到 mdui 的组件中，都要使用 `import mdui from 'mdui'` 导入
