### ISSUE TITLE
官网炸了？？？？

### ISSUE THREAD

**Issue by van23qf** [zdhxiong/mdui#196]
找不到服务器IP

**Comment by Erven2016** [comment]
貌似是DNS解析问题

**Comment by Tsuk1ko** [comment]
服务器 offline 了

![](https://i.loli.net/2019/07/09/5d2429c7f01e293059.png)

**Comment by Erven2016** [comment]
原来如此，一大早想看文档，Chrome 页面提示can't find ip address

**Comment by zdhxiong** [comment]
已恢复
