### ISSUE TITLE
使用压缩后的 JS 时，预定义对话框的回调函数失效

### ISSUE THREAD

**Issue by TransparentLC** [zdhxiong/mdui#197]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 0.4.2
---------------------------
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：Windows / Android
* 浏览器及版本：Firefox 68 (Windows / Android)、Edge 18 (Windows)
* 在线演示：
    * 使用压缩后的 JS（`dist/js/mdui.min.js`）：https://jsbin.com/lawarawili/edit?html,output
    * 使用未压缩的 JS（`dist/js/mdui.js`）：https://jsbin.com/peqitacasi/1/edit?html,output

### 如何操作
使用 `mdui.alert()`、`mdui.confirm()`、`mdui.prompt()` 调用三种预定义对话框，设定按下确认 / 取消按钮的回调函数，然后点击对话框的确认 / 取消按钮。

### 预期结果
运行对应按钮的回调函数，演示中为弹出“点击了确认 / 取消按钮”的提示。

### 实际结果
alert 和 confirm 两种对话框的按钮点击后对话框消失，没有调用函数。
prompt 对话框的按钮点击后对话框不消失，也没有调用函数。
换用未压缩的 JS 后三种对话框均正常消失，正常调用对应函数。

**Comment by zdhxiong** [comment]
更新到 v0.4.3 已修改
