### ISSUE TITLE
帶遮罩的抽屜式導航

### ISSUE THREAD

**Issue by szchenghuang** [zdhxiong/mdui#20]
抽屜式導航在寬屏下是預設開啟，但是設定帶遮罩的情況下，預設開啟的時候並沒有遮罩。

請問這是預料中的動作，或是這裡出現一個小錯誤?

**Comment by zdhxiong** [comment]
这是预料中的动作，不是小错误。

默认带遮罩的情况下，应该默认隐藏抽屉式导航。如果需要显示遮罩且开启抽屉导航的话，可以调用 open 方法来实现。
但是需要默认显示遮罩的场景很少，更多情况下是不需要默认显示遮罩的。
