### ISSUE TITLE
侧边栏滑动BUG

### ISSUE THREAD

**Issue by suikastar** [zdhxiong/mdui#200]
操作系统 `Android 9.0`
浏览器 `Chrome 75.0.3770.143`
目标 `https://www.mdui.org/`
复现流程 如下`GIF` 图所示
![ezgif-4-4de05842d522](https://user-images.githubusercontent.com/53206264/61853021-6d8dc300-aeed-11e9-828b-631cb1332f4b.gif)

**Comment by DFFZMXJ** [comment]
应为Chrome问题导致，几乎所有含`position: fixed;`的元素皆出此问题于Chrome Android。（如[Flarum](https://discuss.flarum.org)侧边栏）
