### ISSUE TITLE
希望增加一个跑马灯控件，类似于Android中顶部的滚动栏

### ISSUE THREAD

**Issue by powerzd** [zdhxiong/mdui#201]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 0.4.3
---------------------------
这是一个（可多选）
* [ ] bug 反馈
* [x] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：如 Android、iOS、Windows、Linux、MacOS 等
* 浏览器及版本：如 Chrome 58.0.3029.110 (64-bit)
* 在线演示：你可以直接在这个模板上编辑：http://jsbin.com/quzokezoko/edit?html,output

### 如何操作
请在这里详细说明你是如何操作导致的问题

### 预期结果
你的操作期望的结果

### 实际结果
你的操作实际产生的结果

**Comment by DFFZMXJ** [comment]
跑马灯是何……Android中顶部的滚动栏是何……

**Comment by powerzd** [comment]
https://element.eleme.cn/#/zh-CN/component/carousel    饿了么的这个效果

**Comment by suwu150** [comment]
这是自己复制代码实现的意思吗，😄

**Comment by DFFZMXJ** [comment]
没错，就是这个意思。顺带一提，

https://codepen.io/dffzmxj/pen/MWmoJvX?editors=1010

做出来个稍微细致点的版本。
