### ISSUE TITLE
涟漪 效果不会自动消失

### ISSUE THREAD

**Issue by lqzhgood** [zdhxiong/mdui#203]
mdui  0.4.3
---------------------------
* [x] bug 反馈
---------------------------
Windows
Chrome/78.0.3896.0 

### 如何操作
点击后 涟漪 效果不会自动消失，需要手动点击别的地方 才会消失
![image](https://user-images.githubusercontent.com/9134671/64765907-9dfdef00-d577-11e9-8756-62e162f5c40d.png)

官方 https://www.mdui.org/docs/selection_control 的示例也是

**Comment by Junzzzz** [comment]
我猜可能是作者自己设计的？
以前我也碰到了 自己补段代码就行了
下面是`checkbox`的
改成`radio`应该可以用
```
.mdui-checkbox input[type='checkbox']:focus:checked:not(:disabled) + .mdui-checkbox-icon {
    -webkit-box-shadow: none !important;
    box-shadow: none !important;
}

.mdui-checkbox input[type='checkbox']:focus + .mdui-checkbox-icon {
    -webkit-box-shadow: none !important;
    box-shadow: none !important;
}
```

**Comment by wrj2009** [comment]
![image](https://user-images.githubusercontent.com/67864454/95584114-c2c0e080-0a6f-11eb-8d52-be3189c521d0.png)
尤其是这个特别奇怪
