### ISSUE TITLE
mdui.org网站中，问答无法发布新问题

### ISSUE THREAD

**Issue by lijialong1313** [zdhxiong/mdui#205]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 0.4.3
---------------------------
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：如 Android、iOS、Windows、Linux、MacOS 等
* 浏览器及版本：如 Chrome 58.0.3029.110 (64-bit)
* 在线演示：你可以直接在这个模板上编辑：http://jsbin.com/quzokezoko/edit?html,output

### 如何操作
点击问答，点击发布

### 预期结果
提示发布成功

### 实际结果
提示服务器错误，抓包结果为：
{"code":100000,"message":"\u670d\u52a1\u5668\u9519\u8bef"}

**Comment by zdhxiong** [comment]
有点 bug，带链接的时候可能发布不了
