### ISSUE TITLE
mdui.JQ.guid() 返回非数字开头 GUID

### ISSUE THREAD

**Issue by mikelei8291** [zdhxiong/mdui#208]
这是一个（可多选）
* [ ] bug 反馈
* [x] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：Windows
* 浏览器及版本：FF 73.0b5

### 如何操作
使用 `$$.guid()` 生成的 GUID 给 node 的 ID 赋值，如果生成的 GUID 以数字开头，则无法使用 `#id` 的 CSS 选择器选择该 node，使用 `[id="id"]` 的 CSS 选择器则没有问题。

![CSS Selector](https://user-images.githubusercontent.com/9620335/73128526-a0159700-3fc8-11ea-93a5-5bbe02842ba0.png)

在 HTML5 的标准里，ID 是可以用数字开头的，但是在 CSS 的标准里不行：
> Since HTML5 it’s been valid to start an HTML element ID with a number. For example `<div id="10">`. From an HTML perspective, that’s fine.
> _Source: https://benfrain.com/when-and-where-you-can-use-numbers-in-id-and-class-names/_

> In CSS, identifiers (including element names, classes, and IDs in selectors) can contain only the characters [a-zA-Z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_); **they cannot start with a digit**, two hyphens, or a hyphen followed by a digit. Identifiers can also contain escaped characters and any ISO 10646 character as a numeric code (see next item). For instance, the identifier "B&W?" may be written as "B\&W\?" or "B\26 W\3F".
> _Source: https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier_

所以如果能改成生成非数字开头的 GUID 就好了。

**Comment by DFFZMXJ** [comment]
加个下划线？规定里似乎未写。
```js
/^[0-9]/.test(guid)?'_'+guid:guid;
```

**Comment by mikelei8291** [comment]
这个 function 应该也被用在了生成一些 mdui 元素的时候，比如这个下拉选择：
![图片](https://user-images.githubusercontent.com/9620335/73232668-da736580-417b-11ea-9481-8981c9933332.png)

所以是不是改一下 `JQ.guid()` 的代码比较好一点呢？

**Comment by hybridsong** [comment]
可以临时的写 $$.uuid() 把原本的替换
这样以后就可以不用动它了
