### ISSUE TITLE
关闭对话框后自动后退

### ISSUE THREAD

**Issue by YieldRay** [zdhxiong/mdui#210]
---------------------------
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：Android
* 浏览器及版本：Chrome 70.0.3538.80
### 如何操作
网页中直接使用mdui.alert()、mdui.prompt()等方法，使网页加载后直接弹出对话框，关闭后，网页会后退。例如：<https://miku.rthe.net/test.html>

### 预期结果
网页仍留在当页

### 实际结果
设出现该问题页面为b，某正常页面为a，从a进入b后，关闭对话框，网页自动回到a

**Comment by zdhxiong** [comment]
如果是打开页面后直接打开对话框，可以这样：
```js
setTimeout(function() {
  mdui.dialog({
    title: 'title',
    content: 'content'
  })
})
```

**Comment by YieldRay** [comment]
若带#mdui-dialog访问
如https://miku.rthe.net/test.html#mdui-dialog
仍然会自动回退

**Comment by YieldRay** [comment]
已解决，关闭对话框前使用`location.hash=location.hash.replace('mdui-dialog','');`
