### ISSUE TITLE
在移动端中drawer打开时一闪一闪的。

### ISSUE THREAD

**Issue by xiaozhe19** [zdhxiong/mdui#211]
---------------------------
这是一个bug 反馈
--------------------------
* 使用平台：ios
* 浏览器及版本：safari(ios13)

在移动端中drawer打开时一闪一闪的。系统为ios，浏览器为safari。

**Comment by xiaozhe19** [comment]
[效果图](https://sm.ms/image/sN6Qpn12afXLikV)

**Comment by angelop007** [comment]
我也发现了此bug；在PC的Chrome 80.0.3987.132（正式版本） （64 位）中，拖拉浏览器改变其宽度置移动端宽度时，并且drawer是open状态，则侧边栏会自动打开其后有黑色半透明遮罩，此时点击遮罩，侧边栏会close但是遮罩层还在，body的class里mdui-locked还在，遮罩层div也还在。。
