### ISSUE TITLE
npm安装后怎么使用主题样式

### ISSUE THREAD

**Issue by zzy-33** [zdhxiong/mdui#213]
npm使用，怎么使用主题样式

**Comment by DFFZMXJ** [comment]
添加`.mdui-theme-primary-首色`和`.mdui-theme-accent-副色`到`body`元素。（理论上，可以是任何容器元素。）

**Comment by zzy-33** [comment]
添加了，样式还是没有

**Comment by zzy-33** [comment]
> 添加`.mdui-theme-primary-首色`和`.mdui-theme-accent-副色`到`body`元素。（理论上，可以是任何容器元素。）

添加了，还是没有样式

**Comment by zzy-33** [comment]
./node_modules/mdui/dist/css/mdui.css
ModuleParseError: Module parse failed: Unexpected character '' (1:4)
