### ISSUE TITLE
如何让 drawer 组件不影响当前页面布局？

### ISSUE THREAD

**Issue by beetaa** [zdhxiong/mdui#218]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 0.4.3
---------------------------
这是一个（可多选）
* [ ] bug 反馈
* [x] 功能建议
* [ ] 新组件或新特性X
---------------------------
* 使用平台：Windows、Linux
* 浏览器及版本：如 Chrome 58.0.3029.110 (64-bit)

### 如何操作
正常使用 drawer 组件，但组件在抽出和隐藏的过程中，会对原页面的宽度进行挤压，从而导致内容变形（container 使用 fluid 布局）。

### 预期结果
可否有一个选项，让 drawer 组件的显示和隐藏均浮动于页面之上，不对页面结构产生影响？

**Comment by zdhxiong** [comment]
overlay: true

**Comment by beetaa** [comment]
@zdhxiong 非常感谢，解决了问题。有个小建议，可以在文档中进行两个地方的优化：

- 对 overlay 属性和影响进行说明，相信有很多人都会直觉认为这个属性是给页面增加一层遮罩，但可能不会意识到可以解决这种挤压页面的问题
- 对 overlay 属性做一个范例。在文档里，overlay 表述为**参数**，其实是可以直接向 `target` 一样作为自定义属性调用的。
