### ISSUE TITLE
可滚动的 tab 显示出了滚动条

### ISSUE THREAD

**Issue by wangweixuan** [zdhxiong/mdui#22]
只在 Mac 上 Webkit 内核的浏览器发现了这个问题。
UserAgent：`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12) AppleWebKit/604.1.2 (KHTML, like Gecko) Version/10.2 Safari/604.1.2`

**Comment by zdhxiong** [comment]
可滚动 tab 本来就是会显示滚动条的，不然怎么滚动呢。

**Comment by wangweixuan** [comment]
显示出滚动条很奇怪啊。
Guidelines 是这样说的：
![](https://storage.googleapis.com/material-design/publish/material_v_10/assets/0B6Okdz75tqQsRUM1elg3VDRxdTg/components_tabs_usage_desktop5.png)
或许可滚动 tab 本来就不适合桌面端吧。

**Comment by zdhxiong** [comment]
目前确实和官方的不太一样。
这个以后看情况再决定怎么改，目前暂时不改。
