### ISSUE TITLE
建议检测 prefers-color-scheme 实现自动深色模式

### ISSUE THREAD

**Issue by kwaa** [zdhxiong/mdui#223]
这是一个（可多选）
* [ ] bug 反馈
* [x] 功能建议
* [ ] 新组件或新特性
---------------------------
### 预期结果
增加 .mdui-theme-layout-auto 作为类名或默认启用，
当 prefers-color-scheme 为 dark 时效果和 mdui-theme-layout-dark 相同。
相关：https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by zdhxiong** [comment]
@xb917 好建议，已实现 https://github.com/zdhxiong/mdui/commit/36a62ba700298f1f79e59578682eff4aba5eeacd
