### ISSUE TITLE
mdui.org网站无法打开

### ISSUE THREAD

**Issue by lijialong1313** [zdhxiong/mdui#224]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 0.4.3
---------------------------
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：如 Android、iOS、Windows、Linux、MacOS 等
* 浏览器及版本：如 Chrome 58.0.3029.110 (64-bit)
* 在线演示：你可以直接在这个模板上编辑：http://jsbin.com/quzokezoko/edit?html,output

### 打开https://www.mdui.org/提示，没有找到dns

**Comment by littlefrogfromthenorth** [comment]
能打开呀，你是不是梯子没搭好

---原始邮件---
发件人: "lijialong1313"<notifications@github.com&gt;
发送时间: 2020年6月17日(周三) 下午3:34
收件人: "zdhxiong/mdui"<mdui@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [zdhxiong/mdui] mdui.org网站无法打开 (#224)




  
在提交 issue 之前，请搜索相关内容是否已被提出。 

请确保你使用的是最新版的 mdui，当前最新版为 0.4.3 
 
 
这是一个（可多选）
  
 bug 反馈 

 功能建议 

 新组件或新特性 
 
  
使用平台：如 Android、iOS、Windows、Linux、MacOS 等 

浏览器及版本：如 Chrome 58.0.3029.110 (64-bit) 

在线演示：你可以直接在这个模板上编辑：http://jsbin.com/quzokezoko/edit?html,output 
 
打开https://www.mdui.org/提示，没有找到dns
