### ISSUE TITLE
MDUI的Tab在Dialog内动态生成时，点击Tab标签会关闭掉Dialog

### ISSUE THREAD

**Issue by qq342063618** [zdhxiong/mdui#225]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 0.4.3
---------------------------
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：Windows
* 浏览器及版本：Chrome版本 78.0.3904.70（正式版本） （32 位）
* 在线演示：你可以直接在这个模板上编辑：http://jsbin.com/quzokezoko/edit?html,output

### 如何操作
动态创建了dialog，然后通过button在dialog-content内动态创建tab标签，点击tab标签时dialog会被关闭

### 预期结果
点击tab应该只是切换tab才对

**Comment by zdhxiong** [comment]
无法复现

**Comment by qq342063618** [comment]
别啊大佬
这是demo   不知道是不是调用方法不对   http://47.245.0.52/asdasd.html#example1-tab2

**Comment by qq342063618** [comment]
> 无法复现

http://47.245.0.52/asdasd.html#example1-tab2

**Comment by zdhxiong** [comment]
> 别啊大佬
> 这是demo 不知道是不是调用方法不对 http://47.245.0.52/asdasd.html#example1-tab2

Tab组件没有实例化

**Comment by qq342063618** [comment]
> > 别啊大佬
> > 这是demo 不知道是不是调用方法不对 http://47.245.0.52/asdasd.html#example1-tab2
> 
> Tab组件没有实例化

多谢
