### ISSUE TITLE
v1.0.0之后 .mdui-hoverable 与 .mdui-shadow-0 冲突

### ISSUE THREAD

**Issue by kwaa** [zdhxiong/mdui#227]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 1.0.0
---------------------------
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：Windows 10
* 浏览器及版本：Chrome 84.0.4147.89 (64-bit)
* 在线演示：
https://codepen.io/kwaa/pen/oNbmrzQ （v0.4.3，有效）
https://codepen.io/kwaa/pen/QWyYXdK （v1.0.0，无效）

### 预期结果
当同时使用 .mdui-shadow-0（或其他不为 1 的值）和 .mdui-hoverable 时，.mdui-hoverable 效果正常

### 实际结果
.mdui-hoverable 无效

**Comment by zdhxiong** [comment]
这两个 class 的功能是冲突的，不应该同时使用。非要同时使用的话，mdui-shadow-0 的权重更高。所以这不是bug

**Comment by kwaa** [comment]
> 这两个 class 的功能是冲突的，不应该同时使用。非要同时使用的话，mdui-shadow-0 的权重更高。所以这不是bug

🤔... 看来我只能另外加css了
