### ISSUE TITLE
无法使用drawer的滑动效果

### ISSUE THREAD

**Issue by 6xingyv** [zdhxiong/mdui#230]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 1.0.0
---------------------------
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：如 Android、iOS、Windows、Linux、MacOS 等
* 浏览器及版本：如 Chrome 58.0.3029.110 (64-bit)
* 在线演示：你可以直接在这个模板上编辑：https://jsbin.com/vukibuhexo/edit?html,output

### 如何操作
请在这里详细说明你是如何操作导致的问题
由0.4.3升级到1.0时
更换了css与js

### 预期结果
你的操作期望的结果
恢复此效果

### 实际结果
你的操作实际产生的结果
原drawer的swipe效果消失

**Comment by zdhxiong** [comment]
无法复现

**Comment by 6xingyv** [comment]
> 无法复现
>新旧对比
新：http://yuuka.top:82/
旧：http://yuuka.top:82/login.aspx

**Comment by zdhxiong** [comment]
没加 `swipe: true` 参数
