### ISSUE TITLE
在 Angular2 应用中无法使用组件

### ISSUE THREAD

**Issue by ziofat** [zdhxiong/mdui#24]
如题。在 Angular 2 中无法使用抽屉和 Collapse，原因不明。其他组件未尝试，应该也有相同情况。

如果通过 HTML 方式调用组件，无任何反应。
如果通过 Javascript 方式，在 new 实例化的时候就会报错：
Cannot read property 'mduiDomDataStorage' of null

该 Angular 2 应用 使用 typescript 编写。

**Comment by zdhxiong** [comment]
如果 HTML 是动态生成的，部分组件还不能直接用 HTML 调用。

实例化报错的问题，检查下在实例化之前 HTML 是不是已经生成。如果 HTML 没有生成就实例化会报这个错误。
