### ISSUE TITLE
从1.0.0版本开始show方法id选择无效

### ISSUE THREAD

**Issue by LinWhite2333** [zdhxiong/mdui#241]
* [x] bug 反馈
---------------------------
* 使用平台：全部
* 浏览器及版本：全部

### 如何操作
var inst = new mdui.Tab('#tab');
inst.show('tab2')

### 预期结果
Tab选项卡，显示指定id的选项

### 实际结果
id选择无效，索引号选择正常

**Comment by LittleTurtle2333** [comment]
#242 已修复

**Comment by zdhxiong** [comment]
fixed #242
