### ISSUE TITLE
主题 & 颜色对话框不显示

### ISSUE THREAD

**Issue by get2333** [zdhxiong/mdui#244]
平台：Windows Edge 89.0.731.0 其他浏览器也能复现。

```
<div class="mdui-table-fluid">
  <div class="mdui-list" mdui-collapse="{accordion: true}">
    <div class="mdui-collapse-item">
        <div class="mdui-collapse-item-header mdui-list-item mdui-ripple">
            <div class="mdui-list-item-content">展开列表</div>
            <i class="mdui-collapse-item-arrow mdui-icon material-icons">keyboard_arrow_down</i>
        </div>
        <div class="mdui-collapse-item-body">
            <a href="#1"></a>
            <a href="#2"></a>
            <a href="#3"></a>
            <a href="#4"></a>
            <a href="#5"></a>
            ...
            ...
            ...
            <a href="#100"></a>
        </div>
    </div>
  </div>
</div>
```

用的主题 & 颜色对话框就是 https://www.mdui.org/docs/ 官网右上角的。当 `mdui-collapse-item-body` 展开后太长时，譬如有 100 个子文件，点击 `mdui-dialog` 不显示对话框。发现是其 `top` 值太大导致，请见下图：

<img width="565" alt="top" src="https://user-images.githubusercontent.com/56919116/103332028-7a7bf200-4aa3-11eb-980a-ac596a1f9d90.png">

**Comment by zdhxiong** [comment]
看不懂你的 collapse 和 dialog 有什么关系。

给出能复现的在线演示代码。

**Comment by get2333** [comment]
> 看不懂你的 collapse 和 dialog 有什么关系。
> 
> 给出能复现的在线演示代码。

https://get2333.github.io/

点开`展开列表`  >>  再点右上角`主题设置`，`dialog` 不显示。

**Comment by zdhxiong** [comment]
> > 看不懂你的 collapse 和 dialog 有什么关系。
> > 给出能复现的在线演示代码。
> 
> https://get2333.github.io/
> 
> 点开`展开列表` >> 再点右上角`主题设置`，`dialog` 不显示。

需要在 html 的最顶部添加 `<!DOCTYPE html>`
