### ISSUE TITLE
如何使用非语义图标？

### ISSUE THREAD

**Issue by Jerome-lara** [zdhxiong/mdui#248]
我看到提供的图标使用方法是语义图标，语义图标可以帮助无障碍阅读理解图标和操作，
但是在使用页面翻译插件的情况下，语义图标会被处理成文字，mdui的官网也有同样的问题，样式会变得很难看，
可不可以提供其它方式调用官方图标？
目前我是使用第三方图标库解决，但是暗黑模式适配问题会比较麻烦。

**Comment by zdhxiong** [comment]
![image](https://user-images.githubusercontent.com/3030330/106566516-5d878280-656b-11eb-9ebf-a7a70244e62e.png)
