### ISSUE TITLE
Dialog组件自动调整div大小问题

### ISSUE THREAD

**Issue by WangNingkai** [zdhxiong/mdui#249]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 1.0.0
---------------------------
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：如 Windows
* 浏览器及版本：如 Chrome 58.0.3029.110 (64-bit)
* 在线演示：你可以直接在这个模板上编辑：https://jsbin.com/fuyedeb/edit?html,js,output

### 如何操作
![mdui](https://user-images.githubusercontent.com/23030927/109475317-850d3480-7ab0-11eb-8fd3-172ca6d21062.gif)

![image](https://user-images.githubusercontent.com/23030927/109475433-ad952e80-7ab0-11eb-84b6-948de80d2415.png)

![image](https://user-images.githubusercontent.com/23030927/109475486-bbe34a80-7ab0-11eb-8040-ae95ca16b4cc.png)

vue3+mdui1.0.1 调用对话框无法实时根据内容大小调整

### 预期结果
自动转换对话框大小

### 实际结果
对话框大小未自动转换

**Comment by zdhxiong** [comment]
可以在 `opened.mdui.dialog` 事件中调用 `handleUpdate` 方法
