### ISSUE TITLE
mdui.JQ的html() 不执行里面包含的script代码

### ISSUE THREAD

**Issue by Wanger** [zdhxiong/mdui#251]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 1.0.0
---------------------------
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
mdui.JQ的html() 内容如果包含 script标签不执行，jq是可以正常执行的，求兼容

**Comment by zdhxiong** [comment]
有这种需求的话直接用 jQuery。mdui.jq 更注重轻量。

**Comment by Wanger** [comment]
好吧，那请问能不能另出一个独立一个不带JQ的 mdui JS？

**Comment by zdhxiong** [comment]
> 好吧，那请问能不能另出一个独立一个不带JQ的 mdui JS？

不能
