### ISSUE TITLE
$(...).css 方法不能设置CSS变量

### ISSUE THREAD

**Issue by DFFZMXJ** [zdhxiong/mdui#253]
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：Windows 10 21H1
* 浏览器及版本：Edge 92.0.902.55 (Official build) (64-bit)
* 在线演示：https://jsbin.com/qujoqiwazu/edit?css,js,output

```html
<style>
  div {
    padding-left: var(--var-one);
    padding-top: var(--var-two);
  }
</style>
<div>这是一个 div 元素，请按 F12 查看它的 style 设定。</div>
<script>
const $ = mdui.$;
  $(() => {
    console.log('log 一下证明这段代码有被执行');
    $('div').css('background', 'teal');
    $('div').css('--var-one', '25px');
    $('div').css({
      'font-size': '26px', //字号能设定，CSS变量就不行。
      '--var-two': '25px'
    });
  });
</script>
```

### 如何操作

用`$('div').css`设定一个CSS变量，比如`--var-one`。

### 预期结果

CSS变量如期设置，打开 F12 后显然可见。

### 实际结果

对CSS变量的设定被忽略，打开 F12 后发现完全没有CSS变量。

**Comment by zdhxiong** [comment]
2.0 已支持
