### ISSUE TITLE
大屏触摸设备的 Drawer 组件会无视窗口大小响应触摸事件

### ISSUE THREAD

**Issue by MisaLiu** [zdhxiong/mdui#258]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 1.0.0
---------------------------
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：任意一个支持触摸的大屏设备（如教学白板、超极本等）
* 浏览器及版本：任何一款支持触摸事件的浏览器
* 在线演示：暂无

### 如何操作
1. 在项目中用任意方式创建一个 Drawer 组件，并设置`swipe`为`true`
2. 在任意一个大屏触摸设备中运行该项目
3. 在页面中随意地向左或向右滑动

### 预期结果
Drawer 不应该受到滑动操作的影响

### 实际结果
Drawer 受到了滑动操作的影响自行展开或收缩

**Comment by zdhxiong** [comment]
正常现象。不想滑动功能就把 swipe 设为 false

**Comment by MisaLiu** [comment]
> 正常现象。不想滑动功能就把 swipe 设为 false

好家伙，根源处解决问题
