### ISSUE TITLE
抽屉式导航内容模糊

### ISSUE THREAD

**Issue by canoziia** [zdhxiong/mdui#259]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 1.0.0
---------------------------
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：Windows
* 浏览器及版本：Chrome 版本 97.0.4692.99（正式版本） （64 位）
* 在线演示：https://jsbin.com/mogabir/edit?html,output

### 如何操作
按照教程新建一个抽屉式导航并输入文字

### 预期结果
正常的文字显示

### 实际结果
文字变得模糊
![image](https://user-images.githubusercontent.com/54797411/151486868-5282267e-8dc0-40b7-9e3d-ed0f15d218a5.png)
试着关掉了 will-change: transform; 属性，然后就恢复正常了，不知道是什么问题。安卓上的chrome没有这种现象

**Comment by DFFZMXJ** [comment]
应该跟Chromium渲染transform的方式有关，看到过很多类似的问题，有的是文字模糊，有的是输入线（文本框下边的那条线）模糊，还有的是在文本框左右出现一个1px的诡异的彩色条（#254）。

在Firefox等浏览器上就不会出现此类问题。

不知道为什么，你的模糊问题在我的Chrome 97.0.4692.99上没成功复现。

**Comment by canoziia** [comment]
好迷惑，先凑合着用了，手机端没影响，我电脑上chrome和edge都是这样
