### ISSUE TITLE
HTML使用vue的时候如何引用

### ISSUE THREAD

**Issue by tomxin7** [zdhxiong/mdui#261]
已经引入
![image](https://user-images.githubusercontent.com/20950984/156186122-d27fe8d0-7679-4a23-8f48-f7155295bc2d.png)

代码如下
![image](https://user-images.githubusercontent.com/20950984/156185982-0197f36a-2afc-4fc6-a3e4-7c054407a43c.png)

会报错
![image](https://user-images.githubusercontent.com/20950984/156186057-2ee56bb0-b53f-4948-8b75-1971dcdd06e0.png)

**Comment by zdhxiong** [comment]
直接从 cdn 引入即可：
`<script src="https://cdn.jsdelivr.net/npm/mdui@1.0.2/dist/js/mdui.min.js"></script>`

想通过 import 导入的话，先学一点 js 模块的基础知识：
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Modules

**Comment by tomxin7** [comment]
直接从 cdn 引入，在VUE中无法使用
![image](https://user-images.githubusercontent.com/20950984/156280666-f842ed6f-ef5d-4d5a-87e6-3840e3854c38.png)

代码如下：
![image](https://user-images.githubusercontent.com/20950984/156280827-588588f6-45e3-4699-a751-19421ee49514.png)

![image](https://user-images.githubusercontent.com/20950984/156280759-8ec2bc87-8bc7-42c3-9272-02d8a468360b.png)
