### ISSUE TITLE
Jsdeliver的CDN不能访问

### ISSUE THREAD

**Issue by gytxtx** [zdhxiong/mdui#263]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 1.0.0
---------------------------
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：如 Android、iOS、Windows、Linux、MacOS 等
* 浏览器及版本：如 Chrome 58.0.3029.110 (64-bit)
* 在线演示：你可以直接在这个模板上编辑：https://jsbin.com/vukibuhexo/edit?html,output

### 如何操作
公共cdn崩溃

### 预期结果
mdui组件正常显示

### 实际结果
你的操作实际产生的结果

![image](https://user-images.githubusercontent.com/62281844/169649825-f4c2b2c2-645b-4e05-9f59-08b6347fb064.png)
由于公共CDN崩溃导致无法正常显示

**Comment by zdhxiong** [comment]
可以自行更换其他cdn
