### ISSUE TITLE
.mdui-img-rounded 的圆角半径无法调整

### ISSUE THREAD

**Issue by DuckDeng** [zdhxiong/mdui#264]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 1.0.0
---------------------------
这是一个（可多选）
* [ ] bug 反馈
* [√] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：Windows
* 浏览器及版本：Microsoft Edge 103.0.1264.62 64-bit
* 在线演示：你可以直接在这个模板上编辑：https://jsbin.com/mobimonidi/1/edit?html,output

### 如何操作
给图片添加 .mdui-img-rounded 后会加上一个圆角，但圆角的半径无法调整

### 预期结果
可以自由调节圆角半径

### 实际结果
文档中没有介绍如何更改半径

**Comment by zdhxiong** [comment]
`.mdui-img-rounded{ border-radius: 10px; }`
