### ISSUE TITLE
对话框的弹出位置偏下

### ISSUE THREAD

**Issue by little-gt** [zdhxiong/mdui#265]
bug 反馈
---------------------------

##描述

在**宽屏浏览器**和**pjax刷新方式的网页**中的**对话框**显示的位置严重偏下。
在**手机**等**屏幕不宽**的设备上显示正常。

##截图

[查看截图](https://www.mdui.org/questions/1459)

**Comment by zdhxiong** [comment]
https://www.mdui.org/questions/264
