### ISSUE TITLE
什么时候可以更新呢？

### ISSUE THREAD

**Issue by ecomter** [zdhxiong/mdui#269]
Google 已经更新到 Material Design 3 了，期待 mdui 更新

**Comment by libsgh** [comment]
别说更新了，官网都~~挂~~墙了，QQ群都解散了，估计是弃坑了

**Comment by Yuuz12** [comment]
#268

**Comment by Ruokwok** [comment]
> 别说更新了，官网都~挂~墙了，QQ群都解散了，估计是弃坑了

QQ群好像是群里有人整了个活，被封了
