### ISSUE TITLE
移动端下，带遮罩的抽屉式导航可以滚动

### ISSUE THREAD

**Issue by MadisonRong** [zdhxiong/mdui#27]
在移动端下，打开一个带有遮罩的抽屉式导航，在遮罩的地方上下滑动屏幕，页面的内容可以跟随着滚动。btw，我给页面的 container 设置了 min-height

**Comment by zdhxiong** [comment]
在 ios 上会存在这个问题。

目前没有完美的解决方案，目前其他框架 bootstrap、foundation 等也都存在这个问题。

**Comment by MadisonRong** [comment]
我测试过，在 Nexus3 上也会出现这样的问题，Nexus3 的系统是 CM 的 Android 5.1.1

**Comment by zdhxiong** [comment]
原因是 `<body>` 元素在 iOS 和 Android 上对 `overflow: hidden` 支持不好。
Android 上的新的浏览器已经不存在这个问题。iOS 依然有这个问题，可能只能等苹果来修复了。

https://bugs.chromium.org/p/chromium/issues/detail?id=175502
https://bugs.webkit.org/show_bug.cgi?id=153852
