### ISSUE TITLE
建了个非官方的MDUI Discord 群

### ISSUE THREAD

**Issue by ayumuate** [zdhxiong/mdui#271]
这是一个（可多选）
* [] bug 反馈
* [x ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：随便
* 浏览器及版本：随便
* 在线演示：
* 
### 如何操作

在 https://discord.gg/9BWeQVdx 加入。

欢迎群主也加入。

**Comment by Bluemethyst** [comment]
Is there an updated link for this Discord server?
