### ISSUE TITLE
js 放在页面顶部时，部分组件错误

### ISSUE THREAD

**Issue by ymh0000123** [zdhxiong/mdui#273]
列表点击之后才显示文字

![image](https://github.com/zdhxiong/mdui/assets/107793048/76dd816f-e7cf-4832-b054-7e1ca1dfc6ff)

**Comment by ayumuate** [comment]
Win 11 Edge 117.0.2045.43 JSBin 上没复现出来。

![image](https://github.com/zdhxiong/mdui/assets/104318715/b3e6ceec-0de3-4068-8bd8-2b4147a79b24)

**Comment by zdhxiong** [comment]
> Win 11 Edge 117.0.2045.43 JSBin 上没复现出来。
> 
> ![image](https://user-images.githubusercontent.com/104318715/276956724-b3e6ceec-0de3-4068-8bd8-2b4147a79b24.png)

直接本地打开文件，可以复现

**Comment by ayumuate** [comment]
> 直接本地打开文件，可以复现

JSBin 里也是，今早一刷新网页就复现出来了。

![image](https://github.com/zdhxiong/mdui/assets/104318715/26e45551-8a2b-4189-a251-ceda9bd1b969)

DevTools 里观察发现，`slot`在点击后才会被插入。应该和[这块代码](https://github.com/zdhxiong/mdui/blob/v2/packages/mdui/src/components/list/list-item.ts#L242)有关。

-----

新发现：和 MDUI 1.0 一样，把 `<script>` 扔到 `</body>` 前边或者给它加个 `defer` 属性都可以修复。

要注意的是，你自己的 JS 代码要在 MDUI 的 `<script>` 执行后执行。
