### ISSUE TITLE
html icon

### ISSUE THREAD

**Issue by whooooo589** [zdhxiong/mdui#276]
icon 暂不支持 html?

**Comment by zdhxiong** [comment]
看不懂你要问什么

**Comment by whooooo589** [comment]
> 看不懂你要问什么

呃表达可能有点问题，就是独立包 @mdui/icons 能引用到html里吗

**Comment by zdhxiong** [comment]
mdui 是 web components 组件库，只能用在 html 页面中，其他环境无法使用，@mdui/icons 也一样

**Comment by whooooo589** [comment]
> mdui 是 web components 组件库，只能用在 html 页面中，其他环境无法使用，@mdui/icons 也一样

呃，在纯html环境中，@mdui/icons 图标会显示不了

**Comment by ChizhaoEngine** [comment]
> > mdui 是 web components 组件库，只能用在 html 页面中，其他环境无法使用，@mdui/icons 也一样
> 
> 呃，在纯html环境中，@mdui/icons 图标会显示不了

一样的问题。我使用npm引入的mdui，配合vue运行时，也出现了这种情况。我即使在入口页尝试cdn引入，也无法解决该问题。

**Comment by fywmjj** [comment]
> > > mdui 是 web components 组件库，只能用在 html 页面中，其他环境无法使用，@mdui/icons 也一样
> > 
> > 
> > 呃，在纯html环境中，@mdui/icons 图标会显示不了
> 
> 一样的问题。我使用npm引入的mdui，配合vue运行时，也出现了这种情况。我即使在入口页尝试cdn引入，也无法解决该问题。

可以去瞅一眼issue[#280](https://github.com/zdhxiong/mdui/issues/280)
