### ISSUE TITLE
建议在 `styles/color.less` 中用 `--md-sys-color` 前缀定义颜色

### ISSUE THREAD

**Issue by kwaa** [zdhxiong/mdui#277]
如题，这样和一些库（如 [`@material/web`](https://github.com/material-components/material-web) 组件库，[`@material/material-color-utilities`](https://github.com/material-foundation/material-color-utilities) 工具库，我的 [`shiraha-colors`](https://github.com/importantimport/shiraha/tree/main/packages/shiraha-colors) 脚本）同时使用时可以避免冲突并减小体积。

**Comment by zdhxiong** [comment]
mdui 使用特有的变量前缀是为了避免和其他库冲突。
你不应该指望不同的库共用同一份变量文件来减少体积，因为不同的库未必能全部和设计规范保持同步更新，共用变量文件会在未来出问题的。
