### ISSUE TITLE
希望V2版本仍然支持通过class来设计组件的功能。

### ISSUE THREAD

**Issue by Edge-coordinates** [zdhxiong/mdui#278]
Web Components 是很好的，但是很多时候，使用class来设计组件（像V1一样）是非常符合开发习惯，兼容方面也更简单的做法。

所以我非常希望作者能够仍然支持V1的那种通过class来设计组件的方案，也许，就像 tailwindcss 一样？

真的是非常优秀的库。

**Comment by zdhxiong** [comment]
没计划支持
