### ISSUE TITLE
mdui 2.0.1版本material icon在页面中无法正常显示

### ISSUE THREAD

**Issue by fywmjj** [zdhxiong/mdui#280]
如图所示
![Screenshot_2023_1104_152053](https://github.com/zdhxiong/mdui/assets/142661449/123abe1d-61e2-4d93-839a-46b5473409a6)
video_file等指的是mdui的icon标签，按理来说正常情况应该是摆一个icon在那里，而不是直接显示icon的标签

最先是使用[mdui官方文档](https://www.mdui.org/docs/2#getting-started)所示的方式从cdn直接引入，后来以为是unpkg.com的问题，于是换到了jsdelivr，结果还是有问题，是什么原因

**Comment by zdhxiong** [comment]
https://www.mdui.org/docs/2/components/icon
图标的 CSS 需要单独引入

**Comment by fywmjj** [comment]
> https://www.mdui.org/docs/2/components/icon 图标的 CSS 需要单独引入

怎么个引入法
![image](https://github.com/zdhxiong/mdui/assets/142661449/1e63c763-4e53-43e8-b5a6-d71076e0d1fc)
我用了[文档](https://www.mdui.org/docs/2/components/icon)中的两种引入方法
![image](https://github.com/zdhxiong/mdui/assets/142661449/6c3c411b-9e2a-4e31-94cf-58755b6656a5)
![image](https://github.com/zdhxiong/mdui/assets/142661449/5916bc28-8d59-4a30-9d12-02e6e69194b3)
![image](https://github.com/zdhxiong/mdui/assets/142661449/3e519f2d-a37a-4063-8ae4-1c6a3bf476ba)
![image](https://github.com/zdhxiong/mdui/assets/142661449/1246628f-4574-47ec-8224-d3eef5546ba6)

都是这种的
![image](https://github.com/zdhxiong/mdui/assets/142661449/fd224b34-e2a0-448c-96a1-9d2a976e7b78)
还是没有material icon

**Comment by zdhxiong** [comment]
```html
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined" rel="stylesheet">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp" rel="stylesheet">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons+Two+Tone" rel="stylesheet">
```

**Comment by fywmjj** [comment]
> ```html
> <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
> <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined" rel="stylesheet">
> <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
> <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp" rel="stylesheet">
> <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Two+Tone" rel="stylesheet">
> ```

靠，夹在文档里的，我还以为是mdui示例代码
