### ISSUE TITLE
动态配色在纯 HTML 中无法使用

### ISSUE THREAD

**Issue by Big-Cake-jpg** [zdhxiong/mdui#281]
`setColorScheme.js` 使用调用 npm 库的方式加载依赖项，而这样的方式无法被普通的 HTML 所识别。
目前是否有什么方法能使动态配色在纯 HTML 环境下生效？

**Comment by zdhxiong** [comment]
没看懂你在问什么。
如果你说的是从 CDN 引入 mdui 的话，所有函数都在 `mdui` 对象下，直接使用 `mdui.setColorScheme()` 即可。

**Comment by Big-Cake-jpg** [comment]
> 没看懂你在问什么。
> 
> 如果你说的是从 CDN 引入 mdui 的话，所有函数都在 `mdui` 对象下，直接使用 `mdui.setColorScheme()` 即可。

好的，感谢解答。
