### ISSUE TITLE
RangeSlider 和 Slider 在设置了step之后行为不一致

### ISSUE THREAD

**Issue by kermanx** [zdhxiong/mdui#283]
> Version: v2.0.2

比如 RangeSlider 和 Slider 均设置 step=10，

此时用JavaScript设置
```javascript
rangeSlider.value = [5, rangeSlider.value[1]];
slider.value = 5;
```
则会发现`rangeSlider.value[0]===5`而`slider.value===10`

**Comment by zdhxiong** [comment]
已修复
