### ISSUE TITLE
mdui2中，mdui-list组件内，使用href时，会异常显示下划线

### ISSUE THREAD

**Issue by daxiaamu** [zdhxiong/mdui#285]
正常情况下没有下划线，但是mdui-list内使用slot=“custom”时，就会出现下划线，且无法通过text-decoration: none来去掉
效果
![image](https://github.com/zdhxiong/mdui/assets/29529412/52a3f279-79f5-4e5a-b8df-9a26e1c024d9)
对应代码
![image](https://github.com/zdhxiong/mdui/assets/29529412/dbbd5335-2652-4ddf-901a-f489c0863b62)

**Comment by zdhxiong** [comment]
已修复
