### ISSUE TITLE
建议输出一个扩展 JSX 类型的 d.ts 文件

### ISSUE THREAD

**Issue by BaffinLee** [zdhxiong/mdui#287]
如题，在 VSCode 中写 JSX 会报错

![image](https://github.com/zdhxiong/mdui/assets/17738556/b7213669-da05-4ad4-a0bc-d1b9a2001c64)

**Comment by zdhxiong** [comment]
你可以自己添加类型声明临时解决这个问题：
```ts
declare global {
  namespace JSX {
    interface IntrinsicElements {
      "mdui-top-app-bar": any;
    }
  }
}
```

后续会考虑打包一个 react 组件库。

**Comment by BaffinLee** [comment]
嗯，我现在自己加了，感谢
