### ISSUE TITLE
mdui-button 的 font-weight 似乎没有传递到内部

### ISSUE THREAD

**Issue by RikkaW** [zdhxiong/mdui#290]
也许在这里面加上 `font-weight: inherit;` 就好了（

https://github.com/zdhxiong/mdui/blob/8bde76d586c5ccbd3d0ee627ae775c4c381296c2/packages/mdui/src/components/button/button-base-style.less#L1-L25

**Comment by zdhxiong** [comment]
是的，要不来个 pr
