### ISSUE TITLE
Card 组件貌似与 VitePress <Content /> 不兼容

### ISSUE THREAD

**Issue by gxres042** [zdhxiong/mdui#293]
这边在用 MDUI 2 给自己的 VitePress 博客写主题，发现一个问题
在 pnpm build 之后，若 VitePress 的 `<Content />` 处在 `<mdui-card></mdui-card>` 里，它不会正确渲染出内容
![image](https://github.com/zdhxiong/mdui/assets/53113178/61a3b12f-d927-4283-b6a1-9c9e799acbf4)
![image](https://github.com/zdhxiong/mdui/assets/53113178/04cf51d5-cd92-4d64-938e-35ceaa0cb92c)
而如果移到 `<mdui-card></mdui-card>` 外面就能够正常渲染
![image](https://github.com/zdhxiong/mdui/assets/53113178/88fb0db5-573e-446d-9039-17a16cbb4da0)
![image](https://github.com/zdhxiong/mdui/assets/53113178/cf23d264-d230-4b5e-8b4b-51358b03641d)

这是属于 MDUI 的问题还是 VitePress 他们自己的问题？><

**Comment by zdhxiong** [comment]
在 vue 中使用 mdui 时，需要进行一些配置：
https://www.mdui.org/docs/2/frameworks/vue

**Comment by gxres042** [comment]
真的不好意思（）这一次用 VitePress 的时候忘记配置这个了
