### ISSUE TITLE
MDUI 2.0 文档文字错误

### ISSUE THREAD

**Issue by gytxtx** [zdhxiong/mdui#294]
在 [常见问题](https://www.mdui.org/docs/2/getting-started/faq) 中 
![image](https://github.com/zdhxiong/mdui/assets/62281844/de8e323d-a49a-403a-b28b-2283cb3ec854)
这一句**使用自闭和标签为何无法显示组件？** 其中的 `自闭和` 语句有误，正确的应该是**自闭合**
![image](https://github.com/zdhxiong/mdui/assets/62281844/0c46ae1c-a5b1-4d35-9f9c-01e89aa4d29a)
![image](https://github.com/zdhxiong/mdui/assets/62281844/4da0ddf4-8373-4923-ad58-647c18746f11)

**Comment by zdhxiong** [comment]
已修复
