### ISSUE TITLE
使用一些工具函数时会导致 body 宽度减小，想请教一下这么设计的意义qaq？

### ISSUE THREAD

**Issue by chillcicada** [zdhxiong/mdui#295]
如下图所示：

![2024-02-03_14-06-58](https://github.com/zdhxiong/mdui/assets/116548943/991603b1-3210-44e3-b0f0-d634d60027c2)

**Comment by ayumuate** [comment]
这个[是 `lockScreen`方法里设定的](https://github.com/zdhxiong/mdui/blob/82c346c9a64baa108abb435c8e9355243b45875f/packages/shared/src/helpers/scroll.ts#L92)，目的是在锁定滚动时用空位填上滚动条占用的空间。但是，群主的这个页面的滚动条在`#app`而不是`body`里，所以填充这个空隙就多余了。

**Comment by zdhxiong** [comment]
lockScreen 方法的bug，已经改了：https://github.com/zdhxiong/mdui/commit/8bde76d586c5ccbd3d0ee627ae775c4c381296c2 等下次发版就行
