### ISSUE TITLE
建议将mdui2 CDN导入的JS文件降级到适合的ES标准

### ISSUE THREAD

**Issue by huajiqaq** [zdhxiong/mdui#298]
cdn的js中有一些代码使用了es2021标准的代码
例如使用到了??= 在电脑端可能没问题 但如果使用的是安卓 webview可能很难得到更新 会报错导致页面无法加载

**Comment by zdhxiong** [comment]
是的，mdui不支持老旧浏览器，基本只支持主流浏览器的最新两个版本。
如果需要支持老旧浏览器，可以使用 mdui 1.0，或换其他组件库。

**Comment by huajiqaq** [comment]
谢谢回复 但是我还是有点疑问 mdui.org是如何在老版本运行起来的?
