### ISSUE TITLE
.mdui-panel-item-title .mdui-panel-item-summary 寬度

### ISSUE THREAD

**Issue by szchenghuang** [zdhxiong/mdui#3]
這兩個類別的寬度沒有在規範裡，是不是可以刪除?

> 
> /* 面板项标题 */
> .mdui-panel-item-title {
>   width: 36%;
>   float: left;
>   font-weight: 500;
> }
> 
> /* 面板项内容 */
> .mdui-panel-item-summary {
>   width: 56%;
>   float: left;
>   color: @color-black-secondary;
> }

**Comment by zdhxiong** [comment]
没有宽度的话怎么确保 .mdui-panel-item-summary 的内容能垂直对齐？

**Comment by szchenghuang** [comment]
在`.mdui-panel-item-title`或`.mdui-panel-item-summary`只有一兩個字內容的狀況下，我想要讓 summary 緊接著 title 放置，只隔著 16px 的 padding，畢竟panel 對我來說不像 table 在對齊上有這麼強烈的要求。但是目前寬度被指定了，所以無法達成。規範裡沒有指定寬度，如果照規範的話是可以的。

至於垂直對齊，同樣沒有在[規範](https://material.io/guidelines/components/expansion-panels.html#expansion-panels-specs)裡。雖然說規範裡面沒有明說，但是從[圖裡](https://storage.googleapis.com/material-design/publish/material_v_10/assets/0B7WCemMG6e0VTFFiWFF4SWVHQ1E/components_material_expansionpanels_spec2.png)看似有一個寬度的控制。

這寬度對齊問題如果可以用`.mdui-col-*`之類的類別來解決應該滿適合的，就是沒試過在`.mdui-panel-item-header`裡能不能放`.mdui-col-*`，估計會有衝突，一般都是`*-col`的元素包含組件，而不是組件包含`*-col`元素。

**Comment by zdhxiong** [comment]
我更新了 panel 的样式，现在只限定了`.mdui-panel-item-title`的宽度，`.mdui-panel-item-summary`的宽度会自适应。

我还是觉得垂直对齐会适合大多数的场景，规范给出的例子中也都是对齐的。

你可以自己添加 CSS 来取消宽度限制：
```css
.mdui-panel-item-title {
  width: auto;
  min-width: 0;
}
```

**Comment by szchenghuang** [comment]
的確我是打算覆蓋寬度的設定。多謝你的建議!
