### ISSUE TITLE
mdui-textfield-error 中的错误信息如何动态修改？

### ISSUE THREAD

**Issue by JarvanMo** [zdhxiong/mdui#30]
mdui-textfield-error 中的错误信息如何动态修改？我试了 mdui.updateTextFields()不好用。

**Comment by zdhxiong** [comment]
改错误信息直接改 `mdui-textfield-error` 中的文本就行了，不需要调用 `mdui.updateTextFields()`。

**Comment by JarvanMo** [comment]
@zdhxiong 我再试试，试过好几次都不好用。可能我用的不对。

**Comment by zdhxiong** [comment]
不行的话你可以写个简单点的demo，我来看看。

**Comment by JarvanMo** [comment]
html:  
``html   
  <div class="mdui-textfield mdui-textfield-floating-label content-margin " style="font-size: 2em">
                                <label class="mdui-textfield-label">密码</label>
                                <input class="mdui-textfield-input" name="password" type="password" />
                                <div class="mdui-textfield-error" id="password-error"></div>
                            </div>
``

Js:

``javascript
     function changeError() {
            var error = document.getElementById('password-error')
            error.innerText = 'error'
            error.style.visibility = 'visible'
        }
``

之前没有设置visibility  导致error一直无法显示，现在error倒是能显示，但是能不能通过js实现和.mdui-textfield-input中pattern 控制一样的效果?

**Comment by zdhxiong** [comment]
你可以自己用 JS 进行验证，验证不通过时在 `mdui-textfield` 元素上添加类 `mdui-textfield-invalid` 把错误信息显示出来。
