### ISSUE TITLE
涟漪动画效果跟进

### ISSUE THREAD

**Issue by for-the-zero** [zdhxiong/mdui#302]
涟漪动画效果是Material 3的一个更新之一，希望跟进

可以参考Google的[Material-web](https://github.com/material-components/material-web)

**Comment by zdhxiong** [comment]
涟漪动画已经内置在各个组件里了，没计划单独写个涟漪组件。

**Comment by for-the-zero** [comment]
不是这个意思，Material 3的涟漪动画效果不一样，至少官网演示的都是旧版的涟漪动画

**Comment by zdhxiong** [comment]
效果以官方的设计规范为准，Material-Web 本身是没有遵守设计规范的
https://m3.material.io/foundations/interaction/states/applying-states#bb39aa13-bbcf-400d-a094-2cd2b7aebcc2

**Comment by for-the-zero** [comment]
确实没有，但是我希望能提供一个选择，默认按规范来，加一个东西就像那样子

不过在Android 12及以上版本，涟漪效果已经成了我说的那样子，而且Material-web明明可以用很早就做好的效果为什么还要重新做一个更难的……

**Comment by zdhxiong** [comment]
mdui是完全按设计规范来的
