### ISSUE TITLE
建议添加超链接组件

### ISSUE THREAD

**Issue by mimiaomc** [zdhxiong/mdui#303]
如题，不是按钮

**Comment by zdhxiong** [comment]
有这个组件的：`<a>`

**Comment by mimiaomc** [comment]
没用的啊？

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by zdhxiong** [comment]
自己去看mdn文档，这里不是学习基础知识的地方

**Comment by mimiaomc** [comment]
啊我的意思是超链接设计和这个设计不符

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by zdhxiong** [comment]
你可以自己写样式让它符合你的设计。不要再回复了，这个issue没有意义。

**Comment by mimiaomc** [comment]
好的，抱歉！
