### ISSUE TITLE
Add focus ring for focusable elements for better accessibility and consistancy

### ISSUE THREAD

**Issue by vollowx** [zdhxiong/mdui#305]
Refs:

- [Material Web](https://material-web.dev) ([Source](https://github.com/material-components/material-web/blob/main/focus/internal/focus-ring.ts))
- Mixed Components (demo no longer available) ([Source](https://github.com/vollowx/see/blob/backup/mixed-components/src/m3/focus-ring.js))

**Comment by zdhxiong** [comment]
Currently, we support styling elements with focus states when navigating using tab and arrow keys. However, the Material Design 3 guidelines do not currently define a focus ring. If such a definition is provided in future guidelines, we will align accordingly.
