### ISSUE TITLE
Styling and Localization Issues When Changing HTML lang Attribute

### ISSUE THREAD

**Issue by fatherofinvention** [zdhxiong/mdui#306]
I've discovered unexpected behavior related to component styling and localization, specifically tied to the `lang` attribute on the `<html>` tag. The framework's components do not render correctly unless the `lang` attribute is set to `zh-CN`. Adjusting this attribute to `en-US` or removing it entirely causes styling issues. Also, despite the page content being in English, alert dialogues are displayed in Chinese. Note, these issues were found when using CDN.

**Steps to Reproduce**:
1. Include MDUI via CDNs in an HTML document.
2. Set the `lang` attribute of the `<html>` tag to `en-US` or remove the `lang` attribute.
3. Observe that the MDUI components (e.g., buttons, alerts) do not retain their intended styling, specifically fonts. Also alert and dialogue text are displayed in Chinese regardless of the `lang` setting when English is expected.

EXAMPLE:
```html
<!doctype html>
<html lang="en-US" class="mdui-theme-dark">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" />
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://unpkg.com/mdui@2/mdui.css">
  <script src="https://unpkg.com/mdui@2/mdui.global.js"></script>
  <title>Hello, world!</title>
</head>
<body>

  <mdui-button class="example-button">open</mdui-button>

  <script>
	const button = document.querySelector(".example-button");
  
	button.addEventListener("click", () => {
	  mdui.alert("Alert description", "Alert Title", () => {
		console.log("confirmed");
	  }, {
		confirmText: "OK"
	  });
	});
  </script>
  
</body>
</html>
```

**Expected Behavior**:
The components should maintain their styling regardless of the `lang` attribute's value, and localization settings (like alert dialogues) should correspond to the set language.

**Actual Behavior**:
Component styling breaks when the `lang` attribute is not `zh-CN`. Alert dialogues default to Chinese, ignoring the page's language setting.

Thank you for your support and the excellent work on MDUI.

**Comment by fatherofinvention** [comment]
`<html lang="en-US" class="mdui-theme-dark">`
![0W2Qu35c2024032305 41 54](https://github.com/zdhxiong/mdui/assets/24985048/e28a1f1a-c793-4e38-85fd-669648943d3a)

`<html lang="zh-CN" class="mdui-theme-dark">`
![ey8vcGuN2024032305 43 28](https://github.com/zdhxiong/mdui/assets/24985048/4e7d7aea-5022-433d-8f38-94bf2979cd12)

Alert in Chinese when lang is set to en-US:
![IND062m52024032305 44 14](https://github.com/zdhxiong/mdui/assets/24985048/46f28f4a-1226-4127-b379-56cfbc6386bf)

![3OlSFkiQ2024032305 44 00](https://github.com/zdhxiong/mdui/assets/24985048/93117f3b-b8d7-41e3-9087-0a60a3886f80)

**Comment by zdhxiong** [comment]
I'll add localization language pack feature in the next version. For now, you can use the `confirmText` property to adjust the `alert` function's text. There's a mistake in your `alert` usage. Here's the correct way:

```js
mdui.alert({
  headline: "Alert Title",
  description: "Alert description",
  confirmText: "OK",
  onConfirm: () => console.log("confirmed"),
});
```

About the styling issue you mentioned when setting the `lang` attribute to `en-US`, I couldn't reproduce it. If you can, please edit the online example to provide the reproduction code: https://jsbin.com/noxequyepa/1/edit?html,output

**Comment by fatherofinvention** [comment]
Hi @zdhxiong , thank you for your guideance on the alert, it worked! Here is the JSBin showing the styling issue. 

https://jsbin.com/fefobuwofa/edit?html,output

You'll see when lang is en or en-US the text is unstyled:
![0p7u6WBw2024032306 19 29](https://github.com/zdhxiong/mdui/assets/24985048/ac777348-8432-4df8-b120-8b38dda518b1)

If you change to zh or zh-CN it becomes styled:
![JmfEeKH12024032306 20 40](https://github.com/zdhxiong/mdui/assets/24985048/f331500e-2dd2-4e4f-879f-a0f23b3e6e7d)

I have confirmed this in Chrome, Arc and Firefox on MacOS.

Thank you.

**Comment by zdhxiong** [comment]
@fatherofinvention Because MDUI doesn't specify a default font, the browser will automatically set the appropriate default font based on the `lang` attribute. You can customize the font styles to your preference, for example:

```css
body {
    font-family: -apple-system, "Segoe UI", "Noto Sans", Helvetica, Arial, sans-serif;
}
```

**Comment by fatherofinvention** [comment]
Thanks @zdhxiong  - didn't realize this was browser behavior, good to know.
