### ISSUE TITLE
mdui.$功能缺失

### ISSUE THREAD

**Issue by for-the-zero** [zdhxiong/mdui#312]
相较于原版jq，你这“jQuery 的六分之一”但jq工具库少了很多实用功能

不如$.post，这玩意竟然不支持post，难怪我用$.ajax的时候只有get

**Comment by zdhxiong** [comment]
`$.ajax` 的用法可以自己看文档。
如果你想要和 jQuery 完全一致的功能，直接用 jQuery 就行了。
