### ISSUE TITLE
组件的icon属性可能使用@mdui/icons吗

### ISSUE THREAD

**Issue by shadow3aaa** [zdhxiong/mdui#321]
在vue3中写<head>有点不方便

**Comment by zdhxiong** [comment]
每个 icon 属性都有对应的 slot，在 slot 中使用 @mdui/icons 即可

**Comment by shadow3aaa** [comment]
> 每个 icon 属性都有对应的 slot，在 slot 中使用 @mdui/icons 即可

这很好，感谢
