### ISSUE TITLE
customElements.json links to wrong files (.ts instead of .js)

### ISSUE THREAD

**Issue by jogibear9988** [zdhxiong/mdui#323]
I have a designer wich supports NPM packages: https://node-projects.github.io/web-component-designer-demo/index.html

I tried to use MDUI directly, but it did not work, cause I parse the custom elments manifest, and yours links to the .ts files instead of the .js files. 
Could this be fixed?

see here: https://github.com/webcomponents/custom-elements-manifest/issues/96#issuecomment-1037495021

**Comment by zdhxiong** [comment]
Fixed in v2.1.2
