### ISSUE TITLE
TextField (outlined variant) grows by 4px when active

### ISSUE THREAD

**Issue by pedzed** [zdhxiong/mdui#327]
**Code:**
```html
<mdui-text-field
    variant="outlined"
    label="Text Field"
    class="p-3"
></mdui-text-field>
```

**Default state:**

![image](https://github.com/zdhxiong/mdui/assets/8146593/53fe9129-8f56-4df1-b3eb-a538237cf7df)

**Active state:**

![image](https://github.com/zdhxiong/mdui/assets/8146593/4f14b286-82b5-42da-abac-6a1d4a455c2a)

**mdui version:** ^2.1.1

**Comment by zdhxiong** [comment]
Fixed in v2.1.2
