### ISSUE TITLE
建议增加dashboard组件

### ISSUE THREAD

**Issue by x-pengg** [zdhxiong/mdui#33]
https://getmdl.io/templates/dashboard/

**Comment by zdhxiong** [comment]
这只是一个页面模板吧，用现有的组件完全可以写出这样一个页面。

**Comment by x-pengg** [comment]
对的，都是卡片组件，但是环线统计图、折线统计图这些貌似还没有

**Comment by zdhxiong** [comment]
这个项目不会有图表组件，你可以找第三方的图表库来实现。
