### ISSUE TITLE
Elements using textContent don't trim whitesapce

### ISSUE THREAD

**Issue by Pupix** [zdhxiong/mdui#330]
Hello,

When using `<mdui-select>` the text value of the items doesn't get trimmed so you end up with something like this:

![image](https://github.com/zdhxiong/mdui/assets/4929965/fd928bad-53a3-4a62-b5e8-5eabd248d5a2)

when writing
```html
<mdui-menu-item value="SCHEDULED">
    Scheduled
</mdui-menu-item>
```

The issue is here https://github.com/zdhxiong/mdui/blob/8fac1677e6bc549c3484473e98ad9fecd80bbda0/packages/mdui/src/components/select/index.ts#L538

and this one could be an issue for some other component https://github.com/zdhxiong/mdui/blob/8fac1677e6bc549c3484473e98ad9fecd80bbda0/packages/shared/src/helpers/slot.ts#L32

`textContent` should be replaced with `textContent?.trim()` I suppose.

There's probably more but can't find them right now.

**Comment by zdhxiong** [comment]
Fixed in v2.1.2
