### ISSUE TITLE
Incorrect Evaluation of hasValue Attribute with 0 in Text Field

### ISSUE THREAD

**Issue by mond210** [zdhxiong/mdui#332]
![image](https://github.com/user-attachments/assets/34e709af-d3d6-49cf-bbcc-3259bceb81ac)

在文本字段中输入值0（数字），但由于hasValue属性为false，标签的位置不正确。这个问题可能是由于在MDUI/packages/mdui/src/components/text-field/index.ts文件的第573行使用了两次否定操作符导致的。当赋值为数字0时，进行两次否定操作会返回false。希望这个问题能够在未来得到修复。

In the text field, a value of 0 (number) is entered, but the label is not positioned correctly because the hasValue attribute is false. This issue may stem from the use of the double negation operator at line 573 in mdui/packages/mdui/src/components/text-field/index.ts. When the value is the number 0, applying the double negation results in false. It would be beneficial to have this issue corrected in the future.

**Comment by zdhxiong** [comment]
Fixed in v2.1.2
