### ISSUE TITLE
Add ability to customize the margin for tooltips

### ISSUE THREAD

**Issue by stavros-tsioulis** [zdhxiong/mdui#333]
Hello. I see the mdui-tooltip component has fixed margins between the component it is attached to. It would be great if we could use our own margins for nicer customization.
https://github.com/zdhxiong/mdui/blob/c9a02de155dce36b3dd3bfbb34da7fe175c376bd/packages/mdui/src/components/tooltip/index.ts#L473-L474

**Comment by zdhxiong** [comment]
In what scenarios do you need to customize these two parameters?

**Comment by stavros-tsioulis** [comment]
To adhere to a design, the tooltip needed to be further from the component than 4 pixels. I worked around it by applying margin in an inner container within the tooltip, but because the background of the tooltip is applied to the topmost container, I ended up having to do some style hacks to not have empty background on the extra offset I created:
```css
#user-tooltip::part(popup) {
  background-color: transparent;
  box-shadow: none;
}
```
