### ISSUE TITLE
Suggestion (docs): Sort components alphabetically

### ISSUE THREAD

**Issue by CarlosEGuerraSilva** [zdhxiong/mdui#335]
It's a bit messy to look up on component list when everything is mixed, would be nice to sort everything alphabetically for better user experience

Actual:

![image](https://github.com/user-attachments/assets/9927d2e2-dc78-4e0c-98d6-331299459205)

Proposal:

![image](https://github.com/user-attachments/assets/aea3749e-aa2d-4c6c-b288-68516e17ee74)

**Comment by zdhxiong** [comment]
Now sorted alphabetically.
