### ISSUE TITLE
Slider component buggy when "min" property is specified on SvelteKit dev server.

### ISSUE THREAD

**Issue by tomikaka22** [zdhxiong/mdui#336]
![Screenshot 2024-07-31 at 12-31-37 ](https://github.com/user-attachments/assets/ce21badb-32c0-4aa8-8f53-4463585702f6)

The component seems to function correctly once the project is built, however it is buggy when using the dev server.

Steps to reproduce:
Create a SvelteKit project, and use the slider component like this:

`<mdui-slider min="40" max="85"></mdui-slider>`

run `npm run dev`

**Comment by tomikaka22** [comment]
Upon further use, I can confirm that it remains broken even after building.

**Comment by zdhxiong** [comment]
`min` and `max` are of number type, you should use them like this `<mdui-slider min="{40}" max="{85}"></mdui-slider>`
