### ISSUE TITLE
似乎没有办法修改使用了 mdui-icon 的组件的字体

### ISSUE THREAD

**Issue by RikkaW** [zdhxiong/mdui#340]
为什么要改字体？因为需要使用原版的 Material Symbols 字体，从而可以使用其可变字体属性。例如，在 NavigationRail 中可以达成，在是否选中、是否 hover、是否 active 之间可以让 `FILL` `wght` 有动画地变化。

效果如下：

![GIF 2024-8-10 14-41-25](https://github.com/user-attachments/assets/cf9fb546-b6d7-40e0-8751-2d91f8bf7b03)

但是现在使用 `mdui-navigation-rail-item::part(icon)` 修改 `font-family` 等属性是无效的。

**Comment by zdhxiong** [comment]
目前还不支持 Material Symbols 字体，你可以用 slot 自定义图标，例如：
```html
<mdui-navigation-rail-item>
  Library
  <span slot="icon" class="material-symbols-outlined">swap_vert</span>
</mdui-navigation-rail-item>
```

**Comment by RikkaW** [comment]
一个个改不太现实，因为到处都在用，而且 material icons 和 material symbols 的小部分图标命名不相同。如果能有通用的改字体的方法还是最好的（

现在是用的 patch-package 把 `components/icon/style.js` 里的 css 给清空，然后再在自己的 css 里给 `mdui-icon`、`mdui-navigation-rail-item::part(icon)` 等等改好字体，是可以工作的。但是 mdui-select 里的 mdui-dropdown 里的 mdui-text-field 的 end-icon 的这样超过一层的 css 不会写了（

**Comment by zdhxiong** [comment]
slot 是很常规的用法，不想用 slot，就只能你自己想办法了
