### ISSUE TITLE
observeResize.js在路由后报错(vue3)

### ISSUE THREAD

**Issue by meowluna** [zdhxiong/mdui#341]
使用下拉组件，经vue-router路由后observeResize.js报错(vue3)：
`observeResize.js:20 Uncaught TypeError: Cannot read properties of undefined (reading 'coArr')`
![Clip_2024-08-12_22-42-41](https://github.com/user-attachments/assets/b85bb54a-dc67-46b7-ae36-e09a8d3b4fa6)

复现步骤：1.点击导航栏切换两次及以上路由
复现链接：[🔗🔗🔗](https://codesandbox.io/p/devbox/observeresize-jsbao-cuo-zz68d5)

**Comment by zdhxiong** [comment]
用了 `keep-alive` 导致的，等后续修复吧
