### ISSUE TITLE
TopAppBar组件的自动padding-top的页面错位问题

### ISSUE THREAD

**Issue by meowluna** [zdhxiong/mdui#343]
mdui版本：v2.1.2，使用vue3

---
~~问题一：TopAppBar组件的自动padding-top的页面错位问题，导致页面内容被遮挡
![Clip_2024-08-14_20-32-05](https://github.com/user-attachments/assets/e8009ba5-c640-43c3-9c61-c8b8fbb30a69)
复现步骤：无
复现链接：[🔗🔗🔗](https://codesandbox.io/p/devbox/incorrect-padding-issue-x34msc)~~

---
问题二：TopAppBar组件的自动padding-top的页面错位问题，添加Transition过渡动画后，进行路由后自动padding-top失效
![Clip_2024-08-14_21-40-34](https://github.com/user-attachments/assets/d83cd38e-fda4-4a87-873e-c4cc5aa5ed43)
复现步骤：1.进入子页面，页面错位，自动padding-top失效
2.返回后原页面也错位
3.刷新后自动padding重新生效
复现链接：[🔗🔗🔗](https://codesandbox.io/p/devbox/incorrect-topappbar-padding-issue-h8nlxy)

**Comment by zdhxiong** [comment]
第一个问题：
看文档：
![image](https://github.com/user-attachments/assets/3ab73b25-e2ad-40f5-8c92-0eab123a5d61)
不希望在 body 上添加 `padding-top` 时，应该指定 `scroll-target` 属性。

第二个问题：
使用了 `keep-alive` 导致的 bug，等后续修复

**Comment by meowluna** [comment]
可是我希望在body上加padding啊，问题是自动加的padding太少了遮挡内容

**Comment by zdhxiong** [comment]
> 可是我希望在body上加padding啊，问题是自动加的padding太少了遮挡内容

你用了两个 TopAppBar 组件，应该只有第一个是希望在 body 上加的，第二个不需要在 body 上加。

**Comment by meowluna** [comment]
明白了，根据文档`其值为可滚动内容的容器的 CSS 选择器或 DOM 元素`，是否可以填入由ref控制的dom元素？
![Clip_2024-08-14_22-55-01](https://github.com/user-attachments/assets/17c8ea37-72b1-4b24-9bdf-9dedfa35a116)

**Comment by zdhxiong** [comment]
> 明白了，根据文档`其值为可滚动内容的容器的 CSS 选择器或 DOM 元素`，是否可以填入由ref控制的dom元素？ ![Clip_2024-08-14_22-55-01](https://private-user-images.githubusercontent.com/62191675/357874527-17c8ea37-72b1-4b24-9bdf-9dedfa35a116.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NDgzMDAsIm5iZiI6MTcyMzY0ODAwMCwicGF0aCI6Ii82MjE5MTY3NS8zNTc4NzQ1MjctMTdjOGVhMzctNzJiMS00YjI0LTliZGYtOWRlZGZhMzVhMTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDE1MDY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMDc2NzAzNmQ0OGViZDhhYTBmYmVhOTYwYWE0MjA1YjU0YThjOTY3NzU4ZWFmYjRmZjM3MWFiYTU2MzMzMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BfRsdbZC8F-XAh4kZkFStdfKTXZvoElmGEI-s_JYuaY)

应该可以的，你可以自己试试

**Comment by zdhxiong** [comment]
fixed in ed2c05467c35a0a0ed510d626b3057a60cb0b1c9
