### ISSUE TITLE
TopAppBar not adding padding-top on body

### ISSUE THREAD

**Issue by fgaudo** [zdhxiong/mdui#344]
Hello,

I created a simple about page using the TopAppBar.
I wanted the bar to be fixed, so i left everything default.

In version 2.0.0 the padding-top gets added without any problems as shown here
![before](https://github.com/user-attachments/assets/57a85e6e-62ba-47f3-a238-8e30bfcf86c9)

from version 2.0.3+ (the ones before give errors) the padding-top does not get added.
![after](https://github.com/user-attachments/assets/0127c818-57ff-4380-91ed-d25554a75445)

This happens in version 2.1.2 too.

In both versions the bar is in position: fixed.
If i manually refresh the page, the padding get's added. If i go back and reopen the page (without refreshing), there's no padding again.

This problem apparently happens only on this page, but there isn't really anything special about it..

I saw briefly #343 (with google translate) but it doesn't seem the same thing.

Am i doing something wrong?
Let me know if you need more infos/details.

**Comment by meowluna** [comment]
Looks pretty similar to my issue. In my case, `<keep-alive>` , which is a component cache feature from vue cause the issue, do you enable such kind of cache feature? One of solution is to manually set `padding-top` as a fixed value for `<body>`

**Comment by zdhxiong** [comment]
Looks like the same bug as #343

**Comment by fgaudo** [comment]
> Looks pretty similar to my issue. In my case, `<keep-alive>` , which is a component cache feature from vue cause the issue, do you enable such kind of cache feature? One of solution is to manually set `padding-top` as a fixed value for `<body>`

I'm using solidjs and solidjs-router.
I did not enable any caching features, but the router could be using something which is not in my control.

The fact that the issue appears when I change the page after refreshing, could be a sign that the router might be involved.

I'll maybe try the scroll-target feature before modifying the body directly.

**Comment by fgaudo** [comment]
I tried wrapping the TopAppBar and other content in another div, and the issue seems to have been resolved. The padding now gets correctly added to the body, though I'm not sure why.

In any case, the issue can be closed.
