### ISSUE TITLE
Select 组件重复选择相同项目会清空选择

### ISSUE THREAD

**Issue by Super12138** [zdhxiong/mdui#346]
`Select` 组件已经选择项目时再次选择相同的项目会变为空值（疑似 Bug）
[项目](https://github.com/Super12138/Hash-Checker/blob/main/frontend/index.html#L55)中的代码：
```html
<mdui-select id="method" value="nullSelect" required>
    <mdui-menu-item value="nullSelect" disabled>请选择方法...</mdui-menu-item>
    <mdui-menu-item value="MD5">MD5</mdui-menu-item>
    <mdui-menu-item value="SHA1">SHA1</mdui-menu-item>
    <mdui-menu-item value="SHA3">SHA3</mdui-menu-item>
    <mdui-menu-item value="SHA256">SHA256</mdui-menu-item>
    <mdui-menu-item value="SHA384">SHA384</mdui-menu-item>
    <mdui-menu-item value="SHA512">SHA512</mdui-menu-item>
</mdui-select>
```
在第一次选择一个值，如`MD5`后，再次点击`MD5`该项就会变成空的。同时[官网](https://www.mdui.org/zh-cn/docs/2/components/select)上的例子也可以复现，如下图：

**第一次选择**
![image](https://github.com/user-attachments/assets/6a847b8b-a6f5-4e12-a6fb-f8ae4bdafef3)
**第二次选择**
![image](https://github.com/user-attachments/assets/76316bde-69a4-4a69-aa6d-4041f4679e32)

**Comment by zdhxiong** [comment]
设计如此，如果不希望为空，可以在选择空值时，赋一个默认值
