### ISSUE TITLE
Feature Request: Add Material 3's Outlined text field

### ISSUE THREAD

**Issue by zii0x** [zdhxiong/mdui#348]
I'd like to request the addition of Material 3's Outlined text field to the mdui library. This would allow users to create text fields with a modern and consistent design, following the Material 3 guidelines.

**Reference:**
[Material 3's Outlined text field specification](https://m3.material.io/components/text-fields/specs#68b00bd6-ab40-4b4f-93d9-ed1fbbc5d06e)

**Benefits:**
Improved user experience: The Outlined text field design is modern and consistent with the Material 3 guidelines, providing a better user experience.
Increased adoption: By adding this feature, mdui would become more attractive to developers who want to create modern and consistent UIs.

#feature request
#material 3
#outlined text field.

**Comment by zdhxiong** [comment]
This feature already exists; please read the documentation: https://www.mdui.org/en/docs/2/components/text-field.
