### ISSUE TITLE
<mdui-button-icon icon="iconname"></mdui-button-icon> are used in the examples but never explained

### ISSUE THREAD

**Issue by kimu-Sky** [zdhxiong/mdui#349]
for example, in [Top App Bar Component example](https://www.mdui.org/en/docs/2/components/top-app-bar)
```html
<mdui-top-app-bar style="position: relative;">
  <mdui-button-icon icon="menu"></mdui-button-icon>
  <mdui-top-app-bar-title>Title</mdui-top-app-bar-title>
  <div style="flex-grow: 1"></div>
  <mdui-button-icon icon="more_vert"></mdui-button-icon>
</mdui-top-app-bar>
```

when I use this in production, no icon appears. only text.

**Steps to reproduce:**
- Create a new MDUI project
- Copy the example code from the [Top App Bar Component example](https://www.mdui.org/en/docs/2/components/top-app-bar)
- Run the project in production mode

**Expected result:**
The <mdui-button-icon> elements should render the corresponding icons (e.g., "menu" and "more_vert").

**Actual result:**
Only the text "menu" and "more_vert" is displayed, without the icons.

**Additional information:**
I've checked that I have the latest version of MDUI installed.
I've tried using different icons and browsers, but the issue persists.

**Screenshot:**
![t](https://github.com/user-attachments/assets/1bd83846-3d73-43cc-ad61-9c3c0201d859)

**Comment by zdhxiong** [comment]
You need to add the icon CSS file yourself: https://www.mdui.org/en/docs/2/components/icon#usage-material-icons

**Comment by kimu-Sky** [comment]
what's the difference between this and [@mdui/icons](https://www.mdui.org/en/docs/2/libraries/icons) ?

**Comment by zdhxiong** [comment]
Each icon in `@mdui/icons` is an independent component that must be imported separately, with each being less than 1kb. Using the CSS file is more convenient but larger, around 600kb. For more details, check the documentation.

**Comment by kimu-Sky** [comment]
I notice some icons are missing, like I can't find this icon [`book_5`](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:book_5:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=book_5&icon.size=24&icon.color=%235f6368)

**Comment by zdhxiong** [comment]
Material icons，not Material symbols
