### ISSUE TITLE
Webstorm documentation displays in chinese

### ISSUE THREAD

**Issue by TechnicalParadox** [zdhxiong/mdui#351]
I followed these instructions but the documentation is displayed in chinese.
---

[WebStorm](https://www.mdui.org/en/docs/2/getting-started/ide-support#webstorm)
[For npm-installed mdui](https://www.mdui.org/en/docs/2/getting-started/ide-support#webstorm-npm)
To enable WebStorm IDE support for mdui installed via npm:

Add the following code to the root of your project's package.json file:
`web-types: ["./node_modules/mdui/web-types.en.json"]`
If package.json already has a web-types property, add ./node_modules/mdui/web-types.en.json to the web-types array. Restart WebStorm after these changes.

**Comment by zdhxiong** [comment]
If you have installed the mdui WebStorm extension, please uninstall it.
If the documentation is still displayed in Chinese, please provide your package.json file for troubleshooting.

**Comment by TechnicalParadox** [comment]
I did not have webstorm extension installed. I installed it and now
documentation is displaying in english so this solves the problem. Thank
you.

**Comment by TechnicalParadox** [comment]
Actually, it's working for some things but not others. Here is my package.json

```package.json
{
  "name": "iai-frontend",
  "private": true,
  "version": "0.2.0",
  "type": "module",
  "web-types": [
    "./node_modules/mdui/web-types.en.json"
  ],
  "scripts": {
    "dev": "vite",
    "build": "tsc -b && vite build",
    "lint": "eslint .",
    "preview": "vite preview"
  },
  "dependencies": {
    "@mdui/icons": "^1.0.2",
    "mdui": "^2.1.2",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-router-dom": "^6.26.2"
  },
  "devDependencies": {
    "@eslint/js": "^9.9.0",
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0",
    "@vitejs/plugin-react": "^4.3.1",
    "eslint": "^9.9.0",
    "eslint-plugin-react-hooks": "^5.1.0-rc.0",
    "eslint-plugin-react-refresh": "^0.4.9",
    "globals": "^15.9.0",
    "typescript": "^5.5.3",
    "typescript-eslint": "^8.0.1",
    "vite": "^5.4.1"
  }
}
```

**Comment by zdhxiong** [comment]
You are using it in React, and you need to set it up according to the documentation for integrating with React.
https://www.mdui.org/en/docs/2/frameworks/react
