### ISSUE TITLE
有几个小疑惑想请教一下

### ISSUE THREAD

**Issue by huajiqaq** [zdhxiong/mdui#352]
有几个问题想请教一下
1.想要让mdui-tabs下的mdui-tab固定顶部必须要设置body为不可滑动 另外mdui-tab-panel的高度也要写死 例如
`<mdui-tabs value="tab-1" placement="top-start" variant="primary">
<mdui-tab value="tab-1" tabindex="0" active="">Tab 1</mdui-tab>
<mdui-tab-panel slot="panel" value="tab-1" style="height: 100vh;" active><div style="height: 3000px;"></div></mdui-tab-panel>
</mdui-tabs>`
但是我发现设置为100vh有时不可以滑动到底部 这个时候我手动计算 height使用calc(100vh - 192px) 192px是我一个个计算得到的 成功了 这就是我的疑惑 请问我这种方法正确吗 我总觉得写死是错误的用法 而且也不太方便
2.关于如何mdui-top-app-bar 或mdui-navigation-drawer一直居于顶部问题
mdui-top-app-bar滑动会让不居于顶部 设置 position为fixed !important 请问这种方法正确吗 好像覆盖了原有的

**Comment by zdhxiong** [comment]
1. mdui-tabs 整体固定到顶部
2. 默认就是固定在顶部，不用做任何修改

**Comment by huajiqaq** [comment]
谢谢回复 不过我还有几个疑问 不知道能不能回复一下
关于第一点 是不是将mdui-tab 固定顶部呢 我感觉一个个好像太麻烦了 
这是额外的
好像mdui-tabs的滚动条好像和 mdui-navigation-bar 并不是那么融洽 滚动条会出现在mdui-navigation-bar 底部 当然这只是视觉上看起来有点别扭 无伤大雅
不过还有一个问题 就是body和 mdui-tab-panel 的滚动条会出现两个 是不是解决方法只能固定height

**Comment by huajiqaq** [comment]
另外我该如何支持mdui-tabs的类似和viewpager的联动 是否考虑支持一些自定义的内容 现在写起来太麻烦了 只能模仿mdui-tabs 写一个

**Comment by zdhxiong** [comment]
1. 不能
2. 设计如此
3. 看具体的实现
4. 支持的，看文档 slot 部分

**Comment by huajiqaq** [comment]
感谢您对 mdui 的支持和维护  很抱歉 可能是我之前表达有问题 我在使用 mdui-tabs 组件时遇到了一些问题 希望能得到您的进一步指导
关于 mdui-tabs 固定顶部的问题：
您之前提到 mdui-tabs 本身已经设计为固定在顶部 但我在实际使用中发现 mdui-tabs 并没有固定在顶部 我根据您的方法尝试做了修改 设置 mdui-tab的position为 fixed 我想确认一下 您所说的“不能”是指 mdui 不会支持 mdui-tabs 的固定顶部功能 还是说我之前的解决方法有问题？
关于 mdui-tabs 和 mdui-navigation-bar 的滚动条问题：
我发现 body 和 mdui-tab-panel 滚动条会出现两个
我目前的实现如下：
```
<mdui-tabs value="tab-1" placement="top-start" variant="primary">
  <mdui-tab value="tab-1">Tab 1</mdui-tab>
  <mdui-tab-panel slot="panel" value="tab-1" style="height: 100vh;">
    <div style="height: 3000px;"></div>
  </mdui-tab-panel>
</mdui-tabs>
```
为了避免出现双滚动条，我是否只能通过固定 mdui-tab-panel 的高度来解决？是否有其他更好的方法？
再次感谢您的帮助和支持！如果您有任何建议或需要更多信息 请随时告知

**Comment by zdhxiong** [comment]
不会支持。

建议你去其他地方寻求帮助。这里仅用于反馈 bug。
