### ISSUE TITLE
Void LICENSE?

### ISSUE THREAD

**Issue by rrangelo** [zdhxiong/mdui#358]
_For english speakers_

Why the v2 branch doesn't have the LICENSE file when the v0 and v1 branches have one?
---
_Para hispanohablantes_

¿Por qué la rama v2 no tiene el archivo LICENSE, cuando las ramas v0 y v1 sí tienen uno?

**Comment by zdhxiong** [comment]
The LICENSE file for v2 is located in the subdirectories of the packages directory.
