### ISSUE TITLE
vue2构建的项目使用mdui2编译报错

### ISSUE THREAD

**Issue by LoveAnd-Share** [zdhxiong/mdui#361]
已经执行过npm install mdui --save
vue版本：2.6.11
mdui版本：2.1.3
![image](https://github.com/user-attachments/assets/fbe314ae-3f3e-4ce5-8810-ee41ae7850c8)
入口文件main.js已经添加了导入文件
![image](https://github.com/user-attachments/assets/00f314d2-c41d-4749-b5f2-01dd91caec1a)
报错提示：
![image](https://github.com/user-attachments/assets/cd113ce7-a9c6-42aa-b8aa-59b750e18c7f)

**Comment by zdhxiong** [comment]
你需要使 vue 忽略 mdui 组件：
```
Vue.config.ignoredElements = [
  // 忽略所有“mdui-”开头的元素
  /^mdui-/
]
```
https://v2.cn.vuejs.org/v2/api/#ignoredElements

**Comment by LoveAnd-Share** [comment]
> 你需要使 vue 忽略 mdui 组件：
> 
> ```
> Vue.config.ignoredElements = [
>   // 忽略所有“mdui-”开头的元素
>   /^mdui-/
> ]
> ```
> 
> https://v2.cn.vuejs.org/v2/api/#ignoredElements

感谢，问题解决了
