### ISSUE TITLE
Snackbar isn't being deleted automatically from the DOM after being closed

### ISSUE THREAD

**Issue by swagliquido** [zdhxiong/mdui#367]
I noticed that when the snackbar closes it still stays in the dom, I believe it would be better if the snackbars got automatically removed from the dom when closed, i don't see any good reason to keep a lot of them hidden in the dom after they've been closed.

**Comment by zdhxiong** [comment]
The snackbar component is added by the developer themselves, so the developer also needs to remove it when it is no longer needed.
You can use the [snackbar function](https://www.mdui.org/en/docs/2/functions/snackbar), which will automatically create the snackbar component and automatically remove it after closing.
