### ISSUE TITLE
涟漪动画的问题

### ISSUE THREAD

**Issue by www295686243** [zdhxiong/mdui#4]
在移动端 如果同时触摸两个带涟漪动画的元素 遮罩不会消失 多按几次遮罩会一直叠加

**Comment by wolfan** [comment]
还有个问题，为什么俺的pc上无涟漪效果呐，但是打开控制台模拟器后又有了。
win10-chrome55

**Comment by zdhxiong** [comment]
@www295686243 这个问题已经确认，会尽快修复。

@wolfan 这个问题我无法重现。你用的是不是支持触摸的显示器？

**Comment by wolfan** [comment]
@zdhxiong 昂，支持触控的。
难道是因为这个？

**Comment by zdhxiong** [comment]
@wolfan 我没考虑到触控屏。支持触摸时只绑定了touchstart，没绑定mousedown。会尽快修复的。

**Comment by zdhxiong** [comment]
两个问题都已修复
