### ISSUE TITLE
文档中的那个调色板不错，建议写入文档中如何使用，能让用户自己切换主题

### ISSUE THREAD

**Issue by qq690712575** [zdhxiong/mdui#42]

**Comment by zdhxiong** [comment]
那个调色板就是在 `body` 添加 `.mdui-theme-primary-[color]`、`.mdui-theme-accent-[color]`、`.mdui-theme-layout-dark` 实现的，在文档的[颜色和主题](http://www.mdui.org/docs/color#theme)章节有介绍了。
可以把用户选择的类名保存在 cookie 或 localstorage 或者服务器上，下次打开页面时自动添加之前设置的类名。
