### ISSUE TITLE
请问有做了下拉选择框吗，在文档好像找不到

### ISSUE THREAD

**Issue by qq690712575** [zdhxiong/mdui#43]

**Comment by zdhxiong** [comment]
还没有做。现在要用的话可以用菜单代替的。

**Comment by zdhxiong** [comment]
已添加 Select 组件。

**Comment by qq690712575** [comment]
感谢

- 发送自我的Sony Xperia™智能手机

---- zdhxiong编写 ----


Closed #43<https://github.com/zdhxiong/mdui/issues/43>.
