### ISSUE TITLE
偶尔出现鼠标滚动无效

### ISSUE THREAD

**Issue by Moidea** [zdhxiong/mdui#47]
浏览器为Chrome v57

不知道什么原因，偶尔网页就像卡了一样，鼠标滚动失效，只能拖动滚动条

**Comment by Hexhu** [comment]
请确保能复现这个问题

**Comment by Moidea** [comment]
操作了几次发现都是这个问题，换了edge浏览器测试正常，然后测试了，官方文档演示站，也同样出现这个问题，操作方式为在右边框随便点击滚动，然后点击左边菜单随便滚动，就会出现这个问题

**Comment by zdhxiong** [comment]
我无法测试出这个问题。这一般是浏览器的问题吧。你确认只有 mdui 的网站上有这个问题，其他网站没这个问题吗？
