### ISSUE TITLE
mdui.org docs “开始使用”一节标题与内容不对应

### ISSUE THREAD

**Issue by longque** [zdhxiong/mdui#5]
![default](https://cloud.githubusercontent.com/assets/8530043/21577110/c90e993e-cf89-11e6-8a8d-f02a2d80658f.png)

涉及页面：
http://www.mdui.org/docs/download
http://www.mdui.org/docs/compatibility
http://www.mdui.org/docs/specs

**Comment by zdhxiong** [comment]
改过来了
