### ISSUE TITLE
强烈建议提供react版本

### ISSUE THREAD

**Issue by MinJieLiu** [zdhxiong/mdui#53]
在 `react ` 应用中，拥有更好的组件化，更容易的状态控制，复用性及性能更好，这是前端发展的趋势所在。

现在开发应用基本上都会用 `react `、`vue` 之类作为 `view` 层脚手架。

类似于 `jQuery ` 语法，在稍微大点的应用中会显得吃力，维护起来相当困难。所以建议提供 `react`  版本。

**Comment by zdhxiong** [comment]
暂时还没有 `react` 版的计划。
`react` 是有许多优点，但它更适合在复杂应用中使用。
`mdui` 的轻量级、无依赖、低学习成本也是 `react` 不具备的。

**Comment by cieldon32** [comment]
> 暂时还没有 `react` 版的计划。 `react` 是有许多优点，但它更适合在复杂应用中使用。 `mdui` 的轻量级、无依赖、低学习成本也是 `react` 不具备的。

那就是只能在html里用了？ 刚尝试了下 layout组建应该有 .mdui-prose的样式， 但是在react工程中没有出现。
