### ISSUE TITLE
新版本js报错

### ISSUE THREAD

**Issue by lyl199655** [zdhxiong/mdui#56]
提示Cannot read property 'contains' of undefined，尝试更换旧版后就正常了，希望解决

**Comment by zdhxiong** [comment]
@lyl199655  说明下你的浏览器版本，在未压缩过的 mdui.js 中的报错行数，最好能给个 demo。

**Comment by lyl199655** [comment]
报错很长，我的邮箱632307861@qq.com，能否给一个qq号，我发截图

**Comment by 85636682** [comment]
这个问题在最新的mdui.min.js修复了吗？我用最新的，还是报这个错！

**Comment by lyl199655** [comment]
作者说了下个版本解决，现在的版本可以把mdui.min,js放在页尾

**Comment by zdhxiong** [comment]
@85636682 @lyl199655 
新版本已发布，直接覆盖更新即可
