### ISSUE TITLE
less 有error

### ISSUE THREAD

**Issue by felixtfl** [zdhxiong/mdui#57]
{ [Error: variable @globalPrimaryColorDegrees is undefined in file /ext/mdui/src/color/less/color.less line no. 7]
  type: 'Name',
  filename: '/ext/mdui/src/color/less/color.less',
  index: 258,
  line: 7,
  callLine: NaN,
  callExtract: undefined,
  column: 45,
  extract:
   [ '',
     '@global-primary-color-degrees-length: length(@globalPrimaryColorDegrees);',
     '@global-primary-colors-length: length(@globalPrimaryColors);' ],
  message: 'variable @globalPrimaryColorDegrees is undefined in file /ext/mdui/src/color/less/color.less line no. 7',
  stack: undefined,
  lineNumber: 7,
  fileName: '/ext/mdui/src/color/less/color.less',
  name: 'Error',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-less',
  __safety: { toString: [Function: bound ] } }

**Comment by zdhxiong** [comment]
报错已修复。
不过直接编译 mdui.less 生成的 CSS 代码不含浏览器前缀，兼容性不好。建议使用自带的 gulp 命令来生成。
