### ISSUE TITLE
README.md 建议提供中国的公共 CDN 库地址

### ISSUE THREAD

**Issue by neoFelhz** [zdhxiong/mdui#60]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 0.2.1
---------------------------
这是一个（可多选）
* [ ] bug 反馈
* [x] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：如 Android、iOS、Windows、Linux、MacOS 等
* 浏览器及版本：如 Chrome 58.0.3029.110 (64-bit)
* 在线演示：你可以直接在这个模板上编辑：http://jsbin.com/pamiyulice/edit?html,output
---------------------------

嗯，我只是想说，MDUI 既然已经提供了 CDNJS 支持，同时 MDUI 框架又像是主要面对国内的 Web 开发者，`README.md` 里应该加一些国内前端公共 CDN 库的地址（它们都在同步 CDNJS 的库），如：

- https://cdn.css.net/libs/mdui/
- https://www.bootcdn.cn/mdui/
- https://cdn.baomitu.com/mdui/

**Comment by zdhxiong** [comment]
已添加 bootcdn

**Comment by neoFelhz** [comment]
嗯好哒ヾ(Ő∀Ő๑)ﾉ
