### ISSUE TITLE
为什么不自适应呢。求助

### ISSUE THREAD

**Issue by hjes** [zdhxiong/mdui#62]
## 请问我在jsp页面用
```
<link href="http://cdn.bootcss.com/mdui/0.2.1/css/mdui.min.css" rel="stylesheet">
 <script src="http://cdn.bootcss.com/mdui/0.2.1/js/mdui.min.js"></script>
```
这两个引入了mdui组件
然后
```
`!div class="mdui-container-fluid">
   !div class="mdui-textfield mdui-textfield-floating-label">
  !/label class="mdui-textfield-label">Email</label>
  !/input class="mdui-textfield-input" type="email"/>
!/div>
!/div>`
```
元素写就被和谐，用符合代替下不好意思。

 

这样使用，打开后页面不自适应是怎么回事呢。

**Comment by zdhxiong** [comment]
http://jsbin.com/suguxakupo/1/edit?html,output
你的例子我试了下，可以自适应的

**Comment by hjes** [comment]
非常感谢你的回复。
我这边确实是这样的写法，然后tomcat发布没有自适应的效果，浏览器是chrome。
然后手机也访问，也没用自适应大小，但是确实不出现滚动条，但是图片，文字什么的就特别小。

**Comment by zdhxiong** [comment]
可能你的 `<head></head>` 里没写这行 `<meta name="viewport" content="width=device-width">`

**Comment by hjes** [comment]
非常感谢您的耐心回答。加了这个属性就可以了。谢谢。
