### ISSUE TITLE
Material Design User Interface LOGO

### ISSUE THREAD

**Issue by KeJunMao** [zdhxiong/mdui#63]
---------------------------
这是一个（可多选）
* [ ] bug 反馈
* [x] 功能建议
* [ ] 新组件或新特性
---------------------------

dalao们可以设计一个 **MDUI LOGO**

## 为什么？

我想将MDUI添加到我博客友链，可是已有模板要求有头像，而MDUI暂时还没有官方LOGO。

**Comment by xbmanh** [comment]
![screenshot_2017-08-29-18-25-15](https://user-images.githubusercontent.com/27915898/29816676-975c396a-8c7a-11e7-8ea5-f262a3ac0a16.png)

**Comment by KeJunMao** [comment]
@xbmanh 这是mdl的，不能直接用。

**Comment by DFFZMXJ** [comment]
用字母代替头像，[我的网站](https://www.dffzmxj.tk)就是这么做的。
![image](https://user-images.githubusercontent.com/35987451/41496173-b3954fdc-716b-11e8-90e2-b47ceff9cc7c.png)
