### ISSUE TITLE
【浅见】新功能推荐+可以参与

### ISSUE THREAD

**Issue by swindforce** [zdhxiong/mdui#65]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 0.2.1
---------------------------
这是一个（可多选）
* [ ] bug 反馈
* [x] 功能建议
* [ ] 新组件或新特性
---------------------------
以下是对mdui的新增功能的个人建议
序：其实刚接触到mdui不长时间，之前都在用其他框架，BS、AMAZEUI、Materialize等等，直到前段时间偶然发现了mdui，可以说是一见倾心，使用简单，运行速度快，兼容性好。下面推荐几个其他框架中，我个人觉得好用的功能，看看是否可行，当然如果需要参与设计+编码的话，我也愿意效劳（十二年研发设计经验，前台+后台+平面等等^_^学很杂）。

1，响应式网格的push和pull功能，意思是在大屏横向显示在左侧的网格+右侧的网格，在小屏显示时，原右侧的网格内容在上，原左侧网格在下。
例如：
```html
<div class="mdui-row">
  <div class="mdui-col-xs-4 mdui-col-xs-push-8">占4格，大屏显示在右侧，小屏显示在上 </div>
  <div class="mdui-col-xs-8 mdui-col-xs-pull-4">占8格，大屏显示在左侧，小屏显示在下 </div>
</div>
```

2，是看大家都提出来的Select标签，这个东西我再说就多余了，你们的研发团队应该早有计划。

3，日期/时间组件，这个真心希望能够加入，看Material UI里的这个组件不错，只是还没测试兼容性怎么样，不好给意见，这里只是希望有一个这样的东西，既可以单独选择日期，又可以单独选择时间（12/24），又可以日期时间都有。  其实H5自带的datetime在移动端特效也不错，只是PC端太挫。

4，动画特效，这个功能虽然漂亮，但是消耗较大，低配置移动端也许会出现卡顿。（之前使用materializecss，它包含动画特效，用高配手机都有点卡顿，低配手机直接就bug关闭了）

以上是个人的浅见，是否采纳由贵团队权衡，顺便想打听一下，下个版本大概什么时候出？或者下下的版本^_^

**Comment by swindforce** [comment]
1的例如下面，div代码被和谐了，在这里补充上

div class=mdui-row
  div class=mdui-col-xs-4 mdui-col-xs-push-8  占4格，大屏显示在右侧，小屏显示在上 end div
  div class=mdui-col-xs-8 mdui-col-xs-push-4  占8格，大屏显示在左侧，小屏显示在下 end div
end div row

**Comment by zdhxiong** [comment]
感谢您的建议，我会仔细考虑。
下个版本会增加几个新组件。

**Comment by swindforce** [comment]
好样的！

**Comment by KenMizz** [comment]
图片放大可以吗,像Materialize一样

**Comment by DFFZMXJ** [comment]
@KenMizz 你可以直接定义width和height实现

**Comment by KenMizz** [comment]
@DFFZMXJ 谢谢
