### ISSUE TITLE
添加完css和js后，复制button代码，没有样式。

### ISSUE THREAD

**Issue by QJesus** [zdhxiong/mdui#66]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 0.2.1
---------------------------
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：如 Android、iOS、Windows、Linux、MacOS 等
* 浏览器及版本：如 Chrome 58.0.3029.110 (64-bit)
* 在线演示：你可以直接在这个模板上编辑：https://github.com/QJesus/mdui-test

 ``` bash
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.3
node: 6.10.1
os: win32 x64
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.3
@angular/compiler-cli: 4.1.3

```

### 如何操作
请在这里详细说明你是如何操作导致的问题

[样例](https://github.com/QJesus/mdui-test)

1. angular-cli.json ->             "scripts": [
                "../node_modules/mdui/dist/js/mdui.js"
            ],
2. styles.css ->  @import url('../node_modules/mdui/dist/css/mdui.css');

### 预期结果
你的操作期望的结果
和此处 https://www.mdui.org/docs/button 一致。

### 实际结果
你的操作实际产生的结果
无颜色。

**Comment by zdhxiong** [comment]
有线上的样例吗？

**Comment by QJesus** [comment]
项目地址：https://github.com/QJesus/mdui-test/

https://github.com/QJesus/mdui-test/blob/master/.angular-cli.json#L21  此处添加了js
https://github.com/QJesus/mdui-test/blob/master/src/styles.css#L3 此处添加了css

**Comment by zdhxiong** [comment]
我搭不起来这个项目，要不你发一下最终生成的 HTML 代码

**Comment by QJesus** [comment]
重新装了angular-cli来建项目，现在可以了。
