### ISSUE TITLE
没有select组件吗？

### ISSUE THREAD

**Issue by SyanH** [zdhxiong/mdui#7]
希望可以有个select组件

**Comment by zjxubinbin** [comment]
同求select组件,要是带搜索框,可以搜索下拉列表的字符的那就更好啦~

**Comment by netcore-jroger** [comment]
select 确实是个大家都会用到的组件。有开发计划吗？如果可以的话，我愿意参与进来编码。

**Comment by zdhxiong** [comment]
近期就会开始开发这个组件。

**Comment by szchenghuang** [comment]
的確需要一個 select 元件，開發完後有助於添加一個 auto-select 元件。

**Comment by x-pengg** [comment]
同求select组件，还有能展示tag那种

**Comment by athrunsun** [comment]
可不可以用menu作为select组件呢？menu和select的区别是？

**Comment by zdhxiong** [comment]
Select 组件已添加。

**Comment by zdhxiong** [comment]
@athrunsun menu 的菜单项是链接或可以绑定一些事件，select 则是原生 `<select>` 的美化版本，在表单中可以直接提交。
