### ISSUE TITLE
mdui.JQ能不能加上ajax方法？这样就不用再为了ajax单独引用一个库了

### ISSUE THREAD

**Issue by xiuqianli1996** [zdhxiong/mdui#72]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 0.2.1
---------------------------
这是一个（可多选）
* [ ] bug 反馈
* [x ] 功能建议
* [x] 新组件或新特性
---------------------------
* 使用平台：如 Android、iOS、Windows、Linux、MacOS 等
* 浏览器及版本：如 Chrome 58.0.3029.110 (64-bit)
* 在线演示：你可以直接在这个模板上编辑：http://jsbin.com/pamiyulice/edit?html,output

### 如何操作
请在这里详细说明你是如何操作导致的问题

### 预期结果
希望能直接用mdui进行简单ajax请求

### 实际结果
你的操作实际产生的结果

**Comment by zdhxiong** [comment]
后续有这个计划
