### ISSUE TITLE
求MDUI 小程序版本

### ISSUE THREAD

**Issue by hurricanetx** [zdhxiong/mdui#74]
* [ ] bug 反馈
* [x] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：微信iOS／Android
* 浏览器及版本： 微信小程序

### 如何操作
在小程序中引用MDUI的框架

### 预期结果
MDUI风格的界面

### 实际结果
MDUI风格的界面

**Comment by zdhxiong** [comment]
并没有这个计划
