### ISSUE TITLE
Tooltip选择器只能选择一个元素？

### ISSUE THREAD

**Issue by openpython** [zdhxiong/mdui#76]
> <div class="mdui-row-xs-3">
    <div class="mdui-col mdui-text-center">
      <button class="mdui-btn mdui-btn-icon" ><i class="mdui-icon material-icons">local_printshop</i></button>
    </div>
    <div class="mdui-col mdui-text-center">
      <button class="mdui-btn mdui-btn-icon"><i class="mdui-icon material-icons">local_printshop</i></button>
    </div>
    <div class="mdui-col mdui-text-center">
      <button class="mdui-btn mdui-btn-icon"><i class="mdui-icon material-icons">local_printshop</i></button>
    </div>
  </div>
</div>

 var inst = new mdui.Tooltip('.mdui-btn', {
     content: '复制到剪贴板',position: 'top'
 });

只有第一个button生效。

**Comment by zdhxiong** [comment]
是的，mdui 中所有组件的选择器都只对第一个元素生效。

**Comment by openpython** [comment]
期望选择所有.mdui-btn元素该怎么写？

**Comment by zdhxiong** [comment]
可以用循环
```
mdui.JQ('.mdui-btn').each(function (i, btn) {
  new mdui.Tooltip(btn, {
    content: '复制'
  })
})
```

**Comment by openpython** [comment]
测试可用。
框架挺好用的，建议选择器做成和jquery兼容的，延续使用习惯，减少学习和迁移成本。
