### ISSUE TITLE
这个框架是基于google官方前端框架MDL修改的吗？

### ISSUE THREAD

**Issue by f2ex** [zdhxiong/mdui#77]
感觉很像 google 的 [MDL 框架](https://github.com/google/material-design-lite) 。

**Comment by zdhxiong** [comment]
不是，和 MDL 没有关系

**Comment by f2ex** [comment]
看起来不错，感谢分享

**Comment by KeJunMao** [comment]
Stupid issue.
Close this issue, please.

**Comment by f2ex** [comment]
@KeJunMao Stupid human ~
