### ISSUE TITLE
vue 下使用表格有问题

### ISSUE THREAD

**Issue by jameskid007** [zdhxiong/mdui#79]
vue 下动态改变数据后，多选框无效了，mdui-tooltip也没有更新，还是原来的数据。 
按照官网提示: mdui.updateTables(); 加入这段代码更新表格，也没有效果.
麻烦看看~

**Comment by zdhxiong** [comment]
表格应该是没有问题的，我写了个例子：
https://jsbin.com/yakenamelu/1/edit?html,output

tooltip 的问题已修复：https://github.com/zdhxiong/mdui/commit/e9e8f6b0749b6976f8b1da5964b8765e2c00c942

**Comment by jameskid007** [comment]
嗯嗯。 多选框好像是没有问题的。 我搞错了。
mdui-tooltip那个还是不能更新。 不能这些操作的吗？
https://jsbin.com/gequzixoja/edit?html,output
初始化的时候，我mdio-tooltip里面的content是dfdfdfd
然后点击add item按钮的时候把content修改为haha,审查元素查看确实也修改成了haha,但是悬浮查看还是显示的dfdfdfd,下面自动生成的tooltip代码并没有重新修改.  
麻烦看看。 谢谢！

**Comment by zdhxiong** [comment]
tooltip 更新后还没有发新版本。过几天会发个新版本。

**Comment by jameskid007** [comment]
好的。 谢谢~
