### ISSUE TITLE
对话框 mdui-dialog - 打开的JS函数应判断 URL hash 是否带参数, 选择性的使用 【?】 或  【&】

### ISSUE THREAD

**Issue by lqzhgood** [zdhxiong/mdui#84]
mdui 版本 0.2.1
---------------------------
* [x] 功能建议
---------------------------

Vue

### 如何操作
例如 Vue 的 Url 为 `http://localhost:8080/#/rentInfo` , 因为 `#` 已经被使用。
目前打开 &mdui-dialog 地址栏会变成 `http://localhost:8080/#/rentInfo&mdui-dialog`
导致 Vue-Router 会识别为 `/rentInfo&mdui-dialog` 这样的路由地址，而不是 `/rentInfo`  导致路由错误。
如果 对话框的HTML 此时写在了 子组件中，因为路由的变更，对话框就挂了。
如果 对话框的HTML 写在全局 index.html 下可以解决，但是感觉怪怪的。

### 预期结果
如果加一个判断，末尾没有参数，则使用 `?__x__&mdui-dialog`  (`__x__` 为任意不重复随机字符) 会比较妥当~

### 实际结果
写完感觉还是自己处理比较好诶，毕竟 mdui 不好处理` 不重复的 __x__`

**Comment by dbFlower** [comment]
你可以选择在init Dialog时设置不改变hash,
```javascript
const dialog = new mdui.Dialog(selector, {
  histroy: false
})
```

via https://www.mdui.org/docs/dialog
