### ISSUE TITLE
手机UC浏览器图标不显示

### ISSUE THREAD

**Issue by Townwang** [zdhxiong/mdui#86]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 0.2.1
---------------------------
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：Android
* 浏览器及版本：UC v11.6.2.948
* 在线演示：图标全转换英文或者不显示,转换的英文也显示不全

### 如何操作
有图标的地方都这样

### 预期结果
我希望有图标的地方兼容大部分手机浏览器

### 实际结果
不显示图标或者转换的英文字体太大导致排版很乱.

**Comment by zdhxiong** [comment]
我用相同版本的 UC 测试了，图标可以正常显示。
你看下是不是图标文件没有加载成功。

**Comment by KeJunMao** [comment]
可以试试 [bootcdn](http://www.bootcdn.cn/mdui/)?

**Comment by Townwang** [comment]
@zdhxiong 会不会是我手机问题  华为荣耀V9 我看官网就是那样
[官方文档导航栏](https://i.loli.net/2017/08/03/598278ba414fe.png)

[官方文档上方的图标](https://i.loli.net/2017/08/03/5982795d41e1b.png)

**Comment by zdhxiong** [comment]
这种情况应该就是图标没加载成功
