### ISSUE TITLE
[bug反馈] 文本域输入会导致 Attempted to assign to readonly property 错误

### ISSUE THREAD

**Issue by hapulb** [zdhxiong/mdui#87]
* 使用平台：Android、iOS、Windows、Linux、MacOS 
* 浏览器及版本：如 Chrome 60.0.3112.78 (64-bit)

### 如何操作
<input> <textArea>的输入操作都会导致一个 

**Uncaught TypeError: Cannot assign to read only property 'data' of object '#<InputEvent>'
    at HTMLDocument.a.proxy (mdui.min.js:6)**错误

不影响实际体验，不过希望尽快修复

**Comment by zdhxiong** [comment]
和 #80 #83 是同一个问题，已经修复了。最快这周末，最慢下周末会发一个版本。
