### ISSUE TITLE
Button动态创建问题

### ISSUE THREAD

**Issue by evilatom** [zdhxiong/mdui#88]
Button动态创建后没有涟漪动画效果
有组件更新函数吗？

**Comment by zdhxiong** [comment]
不需要更新函数的。
检查下是否添加了 `.mdui-ripple`，不然就给出例子。

**Comment by evilatom** [comment]
谢谢  真的是我漏加了  .mdui-ripple
有相应讨论群吗？ 大家可以交流一下

**Comment by zdhxiong** [comment]
没有群
