### ISSUE TITLE
似乎是一个Bug反馈吧

### ISSUE THREAD

**Issue by link9596** [zdhxiong/mdui#90]
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：Android
* 浏览器及版本：Mozilla/5.0 (Android 5.1.1; Mobile; rv:54.0) Gecko/54.0 Firefox/54.0

在Android上用Firefox浏览MDUI官方网站时，MDUI文档里面的内容有一个"查看代码"的功能点击无反应，经过测试，Android其他内核的浏览器也会有同样的问题，望作者进行修复  :)

**Comment by zdhxiong** [comment]
已修复
