### ISSUE TITLE
分割线 组件显示不正常

### ISSUE THREAD

**Issue by ragnaroks** [zdhxiong/mdui#91]
---------------------------
这是一个（可多选）
* [x] bug 反馈
---------------------------
* 使用平台：Windows 10 1703 x64
* 浏览器及版本：如 60.0.3112.101 x64
* 在线演示：http://jsbin.com/lovujunohe/edit?html,output

### 如何操作
将默认的
```html
<div class="mdui-divider"></div>
```
修改为
```html
<div class="mdui-divider mdui-hidden-md-up"></div>
```

### 预期结果
分割线应该正常显示在3段文字之间

### 实际结果
分割线在width<=599px情况下正常显示,在width>=600px的情况下到了顶部

**Comment by zdhxiong** [comment]
分割线上也要加上 `.mdui-col-sm-12`
