### ISSUE TITLE
Trigger click event on file input field failed. If it is a bug?

### ISSUE THREAD

**Issue by xrlin** [zdhxiong/mdui#92]
```html
 <input id="file-name-field" name="image_file_name" class="mdui-textfield-input file-name"
                   placeholder="本地上传"/>
```

Use mdui js.

```js
var $$ = mdui.JQ;
// Would not open the file select dialog after run.
$$('#file-name-field').trigger('click');
```
But when using pure js inistead, open the file dialog succefully.

```js
var fileInput = document.querySelector('#file-input-field');
fileInput.click();
```

I found it make difference in triggering click event in button using mdui.JQ except the file input field.

Besides, Can mdui provide the way to disable ajax's ` content-type option` like jquery. It is useful when submit files using ajax.

**Comment by zdhxiong** [comment]
it is mdui's bug, I wil fix it ASAP.

**Comment by zdhxiong** [comment]
https://github.com/zdhxiong/mdui/commit/20a90f049d92dde2f4d088d8aa2a3075ac09318f
