### ISSUE TITLE
建议有个开发路线图

### ISSUE THREAD

**Issue by achun** [zdhxiong/mdui#93]
* [ ] bug 反馈
* [x] 功能建议
* [ ] 新组件或新特性
---------------------------
今天发现 MDUI，赞啊，里面有太多喜欢的设计，简单列举两个，属性值表达式 mdui-options="...", 轻量的 html5 input 验证。
期望能制定一个设计路线，明确那些是基本的功能(包括TODO), 基本功能会出现在主仓库中。而其他的则作为扩展，不会出现在主仓库中。

这很有意义，避免臃肿在不经意间发生。
具体来说:

请不要过多考虑兼容性问题，可建议用户使用类似 polyfill.io 方案。

可以建立一个单独的笫三方插件列表的仓库，只容纳链接和简介，不存代码，感觉MDUI 会形成一个生态。这个和 NPM ,yarn 不冲突。只是方便查询和交流。

建立模板分享中心，方便更快速的应用。

建议要求所有提出BUG 贴子的给出在线演示，这更有效率。

**Comment by zdhxiong** [comment]
很好的建议，谢谢

**Comment by neoFelhz** [comment]
@zdhxiong 可以试试 GitHub 提供的 [Project](https://github.com/zdhxiong/mdui/projects) 功能
