### ISSUE TITLE
写了个 mutation, 增强对单页面的支持, 求 review

### ISSUE THREAD

**Issue by achun** [zdhxiong/mdui#94]
---------------------------
这是一个（可多选）
* [ ] bug 反馈
* [ ] 功能建议
* [x] 新组件或新特性
---------------------------

其实就是对单页面支持的, 不过功能描述很硬.
不知合不合拍, 请 review, 可以的话就 pr

https://github.com/powjs/mdui/commit/bf5e310bf9a7a474cb12e6d3cef0c38ffd1aa9d4

**Comment by zdhxiong** [comment]
厉害了，等我好好看看代码

**Comment by zdhxiong** [comment]
很好，提交 pr 吧
