### ISSUE TITLE
请问为什么同样的主色和强调色显示效果会不一样？

### ISSUE THREAD

**Issue by XuJinNet** [zdhxiong/mdui#95]
---------------------------
这是一个（可多选）
* [x] bug 反馈
* [ ] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：Windows，MacOS
* 浏览器及版本：Firefox，Chrome，Edge
* 在线演示：https://www.mdui.org/docs/#&mdui-dialog

MDUI 确实是一个很好的 Material Design UI 框架，很好用。
在使用过程中遇到一个问题，主色和强调色同样选择 Teal，但强调色明显感觉要亮很多，颜色表现不自然，期望的显示效果是和主色一样。不知说得是否正确，请指教……

**Comment by zdhxiong** [comment]
强调色确实应该比主色亮。主色往往用于大色块，强调色用于小块用于强调的元素，如按钮。

MDUI 的颜色和官方设计规范是完全一致的。
https://www.mdui.org/design/style/color.html#color-color-tool

**Comment by XuJinNet** [comment]
好的，谢谢指教 👍
