### ISSUE TITLE
建议去掉标签文本缩放 .75, 不好看

### ISSUE THREAD

**Issue by achun** [zdhxiong/mdui#97]
---------------------------
这是一个（可多选）
* [ ] bug 反馈
* [x] 功能建议
* [ ] 新组件或新特性
---------------------------
规范里说标签和文本输入字体大小要一样的,

![image](https://user-images.githubusercontent.com/489285/30807061-dd39c936-a1bd-11e7-8cf2-9792a98d7a92.png)

特别是对中文

![image](https://user-images.githubusercontent.com/489285/30806965-7bb4fc76-a1bd-11e7-9945-f85af75a46e6.png)

https://www.mdui.org/docs/textfield/demo2 

源码

https://github.com/zdhxiong/mdui/blob/51e32855bf6f8656d9e36d30961aa3ce2af1ee52/src/textfield/less/textfield.less#L59

**Comment by zdhxiong** [comment]
”标签文本和输入文本字体大小相同“ 指的是默认状态下。
默认状态下为 16sp，聚焦状态为 12sp，正好缩小到 0.75。

**Comment by achun** [comment]
哎呀, 这个固定标签, 也就是所谓的聚焦状态, 中文好小,,,,
好吧, 感觉这个还是跟着规范走吧. 嫌小的走 diy :-) 或 浮动标签吧
