### ISSUE TITLE
表格样式

### ISSUE THREAD

**Issue by snoopy1996** [zdhxiong/mdui#98]
* 在提交 issue 之前，请搜索相关内容是否已被提出。
* 请确保你使用的是最新版的 mdui，当前最新版为 0.3.0
---------------------------
这是一个（可多选）
* [] bug 反馈
* [x] 功能建议
* [ ] 新组件或新特性
---------------------------
* 使用平台：Windows
* 浏览器及版本：Chrome
* 在线演示：你可以直接在这个模板上编辑：http://jsbin.com/nizivuwevu/edit?html,output

### 问题建议
* 表格样式单一，且单元格高度有点大，只能复写 CSS 来调整
* 没有对应的分页组件的样式

* 希望能加一些调整高度的类 
* 可以有完全border 的样式
* 有匹配的分页组件

**Comment by zdhxiong** [comment]
表格功能确实可以考虑强化一下。

**Comment by lzh370** [comment]
希望有紧凑表格样式
