### ISSUE TITLE
mdui-card能否流式布局

### ISSUE THREAD

**Issue by ragnaroks** [zdhxiong/mdui#99]
---------------------------
这是一个（可多选）
* [ ] bug 反馈
* [x] 功能建议
* [ ] 新组件或新特性
---------------------------

### 预期结果
![2](https://user-images.githubusercontent.com/7598199/31478361-6d4b74b6-af42-11e7-99ab-fb51ca9867b0.png)

### 实际结果
不等高卡片多了以后看起来非常不协调
![1](https://user-images.githubusercontent.com/7598199/31478364-7381cd1c-af42-11e7-9c60-19e6f32ee2fb.png)

### 当前兼容方法
```javascript
//两栏以上则调整高度
if (document.body.clientWidth > 600) {
    var card_height = 0;
    //lodash兼容古代浏览器
    window.lodash.forEach(document.querySelectorAll('.mdui-card'), function(v, i) {
        card_height = (v.clientHeight > card_height) ? v.clientHeight : card_height;
    });
    window.lodash.forEach(document.querySelectorAll('.mdui-card'), function(v, i) {
        v.style.height = card_height + 'px';
    });
}
```
![3](https://user-images.githubusercontent.com/7598199/31478459-156cc44c-af43-11e7-95b3-095852c12121.png)

**Comment by zdhxiong** [comment]
流式布局建议配合第三方插件来实现。
